<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DetailPemindahan.Nominal</name>
   <tag></tag>
   <elementGuidId>14126035-1ca8-4b06-a6d4-266c339854bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DetailPemindahan_Nominal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DetailPemindahan_Nominal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2b58dfa-0979-4b73-862a-120bc8a471cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-5</value>
      <webElementGuid>807629f3-afb5-4eb5-801b-35caeefa544a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>19fa4087-1d0e-4537-863d-79832173f756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Nominal must be a number.</value>
      <webElementGuid>bb7c3f65-a121-47cb-acd3-461619194329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DetailPemindahan_Nominal</value>
      <webElementGuid>b7e68b21-2b1c-40ae-8ccd-703c71269bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DetailPemindahan.Nominal</value>
      <webElementGuid>332619b7-0bed-4ffa-bcb5-72af7e339042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>calculateKursApproval()</value>
      <webElementGuid>5b234afa-52ab-4a13-a84c-0135bf7b4507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b70b3dc-c9f6-41de-8f0c-da4071b35907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c6e8f672-7214-4da6-bfcc-4be307720757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DetailPemindahan_Nominal&quot;)</value>
      <webElementGuid>4874bcb9-af30-4ed4-9065-3dea653d6fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DetailPemindahan_Nominal']</value>
      <webElementGuid>098f5d8a-e3cd-49a1-b2a1-571f1ff615c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-tabs-one-tabContent']/div[3]/div/div[2]/input</value>
      <webElementGuid>d4ea404d-43f3-48eb-87f7-49b2f0eb3726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>28cdb55d-346b-437b-8d6f-49cfe90ba13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DetailPemindahan_Nominal' and @name = 'DetailPemindahan.Nominal' and @type = 'text']</value>
      <webElementGuid>17cd00d8-8b29-438e-92ea-80437b9617f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
