<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PerubahanDebit_NoRekSingleSide</name>
   <tag></tag>
   <elementGuidId>614253cc-8919-4f36-b501-eb6a23a405a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NoRekSSDB']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NoRekSSDB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>430eba81-a1b8-4e75-aac5-6b49b61f3734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-7</value>
      <webElementGuid>1e16e008-5aa5-4f6b-bca8-21dcadda7548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NoRekSSDB</value>
      <webElementGuid>5c07ca53-7890-47b4-a5f2-11036401bf22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PerubahanDebit.NoRekSingleSide</value>
      <webElementGuid>d7a55c8f-923e-4560-84e7-0188a108c274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73596901-8f7b-486c-9ed7-a8690c0242fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f7d1ea69-9936-49f3-9715-76a82fd8cc89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NoRekSSDB&quot;)</value>
      <webElementGuid>b0f7abe0-2bb0-44c5-9745-537654103f4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NoRekSSDB']</value>
      <webElementGuid>f42e398b-38a1-45da-9828-93dec4c44c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noRekSingleSideDb']/input</value>
      <webElementGuid>205e4aa3-e444-48ec-ac88-77e41960d3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/input</value>
      <webElementGuid>7dc35a3e-fb09-4522-b7b5-c344120646b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NoRekSSDB' and @name = 'PerubahanDebit.NoRekSingleSide' and @type = 'text']</value>
      <webElementGuid>54fcb3d5-c103-46cd-8e94-5d66c1a1bd81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
