<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Perubahan_Debit_NoRekening</name>
   <tag></tag>
   <elementGuidId>c2273d6b-ef94-4968-9c6b-9f25e7d15ee6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PerubahanDebit_NoRekening']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PerubahanDebit_NoRekening</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>362ba2d9-1e88-4509-a973-b6f17d487aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-7 inputnumeric</value>
      <webElementGuid>a3988f0b-fb50-4a00-873a-414ec1d5b7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>56e37ad9-bfe4-453a-a351-f1dec8e0b653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NoRekening field is required.</value>
      <webElementGuid>aa1462f7-ad8a-4199-8051-6848d4f906b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PerubahanDebit_NoRekening</value>
      <webElementGuid>a0bb96f8-155f-4e9a-9d83-e31daf2b145c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PerubahanDebit.NoRekening</value>
      <webElementGuid>896f3f9e-29f7-42ff-8e66-f794af2bee34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca8b1474-4190-4930-8fc5-8b8bd85ebe70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8247b86c-cbfe-4fed-a195-aad404cb3e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PerubahanDebit_NoRekening&quot;)</value>
      <webElementGuid>6fe552c4-fdb2-404f-b874-0c3320d9b725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PerubahanDebit_NoRekening']</value>
      <webElementGuid>dd3b58a2-f18f-43b8-b3fe-2f6f8108be6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divSSDB']/div[2]/input</value>
      <webElementGuid>ce8f2d77-b1f7-4c5e-8abe-9554f5c07ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>9f56838d-4ced-4d95-99ad-a9f7162b6a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PerubahanDebit_NoRekening' and @name = 'PerubahanDebit.NoRekening' and @type = 'text']</value>
      <webElementGuid>d2d667e1-6e01-4e9d-b55f-2adcffeeed9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
