<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoRekKredit</name>
   <tag></tag>
   <elementGuidId>31ed4a2b-46b6-4aed-96fa-ca7cc98f2911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NoRekKredit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NoRekKredit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c80c7518-756b-402a-aaf8-9a4249ca8284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-7 inputnumeric</value>
      <webElementGuid>4437452c-9510-4b79-ba94-e72635d01b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>468a4279-b3f9-4ddd-8623-c62e0c1d3b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NoRekKredit field is required.</value>
      <webElementGuid>0065430b-f0de-463a-9d77-10856d832da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NoRekKredit</value>
      <webElementGuid>d432e2d7-0b36-4070-b7eb-1b7e9d0d07d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NoRekKredit</value>
      <webElementGuid>039df799-6227-4b88-b5f2-c21fd9cd6a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>copyRekKredit()</value>
      <webElementGuid>d3298761-c873-4c9b-abc9-a7c505ccf166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>292b079e-17e1-4c69-bada-fbe0882df664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d98b15e7-6746-4959-bde8-b8d39c1e4275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NoRekKredit&quot;)</value>
      <webElementGuid>e3672b5e-69ab-4242-974b-5cfe90341417</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NoRekKredit']</value>
      <webElementGuid>3b25bfc5-2397-486b-8ce4-3ff07590ca1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-tabs-one-home']/div[2]/div[2]/div/input</value>
      <webElementGuid>03b78e5c-3a6e-4691-a548-b1b559cd42b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>a82dbbd0-90e4-4767-bb08-e725ed3a29b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NoRekKredit' and @name = 'NoRekKredit' and @type = 'text']</value>
      <webElementGuid>ac501427-08ab-4829-b4f4-94d262656cee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
