<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Pencairan Kedua dan Sterusnya</name>
   <tag></tag>
   <elementGuidId>8ac7429c-06a5-4ab7-b69a-114152e37248</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='custom-tabs-one-home']/div/div/div/div/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4634ad6a-a9e6-4a21-bd77-06b45e4f3a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>pencairankedua</value>
      <webElementGuid>2a3a12a5-a82b-42ed-a236-2f7f771f30f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label</value>
      <webElementGuid>7bdedd6d-f982-40b6-a46a-3a6cfd2bf4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pencairan Kedua dan Sterusnya </value>
      <webElementGuid>20db0254-d6ff-49e7-86ce-0f2234091289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-tabs-one-home&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group row&quot;]/div[1]/div[@class=&quot;custom-control custom-radio&quot;]/label[@class=&quot;custom-control-label&quot;]</value>
      <webElementGuid>f14d2208-cfa6-4885-b521-10f06e195242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-tabs-one-home']/div/div/div/div/div[2]/label</value>
      <webElementGuid>045e4a7e-b2b4-4f44-b711-e432d76e24bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>196ccc8e-b260-48b6-a84a-11e337fc3a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Pencairan Kedua dan Sterusnya ' or . = 'Pencairan Kedua dan Sterusnya ')]</value>
      <webElementGuid>f6e2744f-951e-4aee-ba8f-22bb8b1fe936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
