<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_DetailPemindahan.Narasi</name>
   <tag></tag>
   <elementGuidId>9a36579a-0c74-4887-b332-f7ed23e192c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='DetailPemindahan_Narasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DetailPemindahan_Narasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1be8324e-2ab5-45da-9089-c4e00f2219e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-7</value>
      <webElementGuid>21ba6267-fae7-4386-be40-f933b93819d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6569b969-03b4-4a47-8324-22cf9deaa074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Narasi field is required.</value>
      <webElementGuid>30a9e00d-5e32-4a1f-8b17-110510eafa45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DetailPemindahan_Narasi</value>
      <webElementGuid>accfb500-a6c6-4941-bdd9-3520414b27e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1fc4b4aa-3121-49e6-b64d-d5f4ddd9388e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DetailPemindahan.Narasi</value>
      <webElementGuid>cbbbce6e-394d-46f3-b537-c418fff69f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DetailPemindahan_Narasi&quot;)</value>
      <webElementGuid>6a301e14-b179-4942-8174-f50cebb1d143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='DetailPemindahan_Narasi']</value>
      <webElementGuid>a50a37fd-ba5b-49c2-bfd8-a554e1f8c275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-tabs-one-tabContent']/div[3]/div/div[4]/textarea</value>
      <webElementGuid>d15dd72c-2d46-4e1f-887f-aaecfe8191df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>96dfc0f0-30f5-4c6b-b6da-1c57ca9324e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'DetailPemindahan_Narasi' and @name = 'DetailPemindahan.Narasi']</value>
      <webElementGuid>6e5f8290-edd9-4a03-920f-4d0b1a710c66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
