<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_DetailPemindahan.NarasiTambahan</name>
   <tag></tag>
   <elementGuidId>d7973260-5ca5-438c-a8b3-5eb1b4ecb2bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='DetailPemindahan_NarasiTambahan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DetailPemindahan_NarasiTambahan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8d2edf25-bf24-4882-bcb8-15e5751d6cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-7</value>
      <webElementGuid>811280c4-cbdc-4880-865d-00169950c306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>29bd0698-28ce-44d0-a28a-8b5846c56086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NarasiTambahan field is required.</value>
      <webElementGuid>74817d39-ab4e-4a58-b7f1-104afea05404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DetailPemindahan_NarasiTambahan</value>
      <webElementGuid>1856d6fe-f079-453a-bf15-ee2349704ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>84a421a0-b658-48ea-89b0-629456247c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DetailPemindahan.NarasiTambahan</value>
      <webElementGuid>ad525c34-c144-4281-9ab7-28bbda737efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DetailPemindahan_NarasiTambahan&quot;)</value>
      <webElementGuid>dee59bdf-bf69-480a-9009-908788d7f472</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='DetailPemindahan_NarasiTambahan']</value>
      <webElementGuid>fffe1bc9-4b93-4c7f-8ce7-cece265021f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-tabs-one-tabContent']/div[3]/div/div[5]/textarea</value>
      <webElementGuid>e13a08e8-419e-48c9-9dd6-e6bc77b8e659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/textarea</value>
      <webElementGuid>c799920b-d71a-41e3-af8a-28462f248cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'DetailPemindahan_NarasiTambahan' and @name = 'DetailPemindahan.NarasiTambahan']</value>
      <webElementGuid>0958d18f-4afd-4ac7-b6d8-6f527107b6af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
