<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Dokumen Underlying</name>
   <tag></tag>
   <elementGuidId>dbe2ee1f-bbbe-4f48-a4ff-0fdd78a903a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='listFileContainer']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.form-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7eddbf01-fea7-470f-815b-cffe44df183e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>listFile</value>
      <webElementGuid>f42f265e-8c64-497f-9c4f-43d1724abaae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>5c12d81b-06ea-475a-9a3e-44ce6f98550a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dokumen Underlying</value>
      <webElementGuid>c1ffa22f-ce58-4cc4-9731-e57caaec5d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listFileContainer&quot;)/label[@class=&quot;form-label&quot;]</value>
      <webElementGuid>75ed2f98-928c-4b17-8810-68a43db126f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='listFileContainer']/label</value>
      <webElementGuid>0350f803-2e96-4596-a8a1-482e2ac1a838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/label</value>
      <webElementGuid>48eb8efd-1924-47ec-9c9e-eedbdd9687ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Dokumen Underlying' or . = 'Dokumen Underlying')]</value>
      <webElementGuid>8a197610-f125-491d-b885-3c9f783e7ec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
