<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Kategori Underlying</name>
   <tag></tag>
   <elementGuidId>0a220923-e940-46ca-b6dd-379dad99b397</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='kategori']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kategori</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>432f4991-1f64-4d73-9cdf-11c2f45ad7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select rounded-0</value>
      <webElementGuid>3947c3d8-81ef-4129-bf74-6eba90039be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kategori</value>
      <webElementGuid>9867769f-ae7b-4b05-bb64-6680cfb0dfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Kategori--Memo BisnisPersetujuan KreditMemo &amp; Persetujuan KreditDokumen Pendukung LainnyaRevisi Memo BisnisForm / ChecklistCover LetterNota / Invoice</value>
      <webElementGuid>c935cc46-f22d-4885-86a7-a0b5ad410024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kategori&quot;)</value>
      <webElementGuid>87dc351c-4f34-46cb-bb58-bf7324f5a411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='kategori']</value>
      <webElementGuid>023e7756-127c-44f4-a91b-0a0319fac7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditForm']/div/div/div/div/div/select</value>
      <webElementGuid>385e85fa-f7d0-488d-840f-18a2d04063e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/select</value>
      <webElementGuid>26206940-df13-49e1-8f8b-1dbc2515daf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'kategori' and (text() = '--Kategori--Memo BisnisPersetujuan KreditMemo &amp; Persetujuan KreditDokumen Pendukung LainnyaRevisi Memo BisnisForm / ChecklistCover LetterNota / Invoice' or . = '--Kategori--Memo BisnisPersetujuan KreditMemo &amp; Persetujuan KreditDokumen Pendukung LainnyaRevisi Memo BisnisForm / ChecklistCover LetterNota / Invoice')]</value>
      <webElementGuid>3dc1f1a1-e0b2-44c0-882f-f684e9e359c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
