<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Narasi2_Tambahan</name>
   <tag></tag>
   <elementGuidId>e5b1bff0-2e0f-477b-87f6-35b1a7c1196f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NarasiTambahan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NarasiTambahan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa21dd49-f92d-4e8f-97bd-6ea7a41415ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-10</value>
      <webElementGuid>511cc62f-c28a-4750-8082-6f1b33093933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6aa5162e-44e2-460b-89e5-ae8a702c381d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NarasiTambahan field is required.</value>
      <webElementGuid>5543d51f-130a-4254-9865-9b61dbe25b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NarasiTambahan</value>
      <webElementGuid>756babcd-7d06-4bd6-b8dc-05f95c0c41e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f3267b55-5cc2-44a6-b37d-bf7bf96e9b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NarasiTambahan</value>
      <webElementGuid>0dad7eb7-335e-4ba1-bb59-82102fe536c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Narasi Tambahan</value>
      <webElementGuid>c28313ff-4664-4ff5-8b1e-d67a976fede5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7a92671-fd0e-45bd-80c2-b3522a17dcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f4934b49-37fc-4fb9-bb15-91eea8acc714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NarasiTambahan&quot;)</value>
      <webElementGuid>d1a87bdf-9171-42a5-b309-d92fb202910f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NarasiTambahan']</value>
      <webElementGuid>b513a30c-6b4d-42fe-8f07-9b4b2bd9d7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PenutupanRekeningForm']/div[5]/div/div[4]/input</value>
      <webElementGuid>6fc10cea-0b2b-4456-89da-65d1662c9127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[4]/input</value>
      <webElementGuid>d40217e7-a365-4244-90ad-a65f31ca74c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NarasiTambahan' and @name = 'NarasiTambahan' and @placeholder = 'Narasi Tambahan' and @type = 'text']</value>
      <webElementGuid>2c0ca43c-a20a-4667-9241-310cf2e81a1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
