<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SaldoEfektif</name>
   <tag></tag>
   <elementGuidId>b3a25afa-c949-4ba0-ab24-f998bd9d7586</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InquiryPelunasan_SaldoEfektif']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#InquiryPelunasan_SaldoEfektif</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da8d4d55-4942-47c6-814e-9af96261879f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-7 nominal</value>
      <webElementGuid>888d84bb-1822-4d86-ae79-5279acb9321a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>388ec3a8-1396-4b91-ab90-1efb3a286580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field SaldoEfektif must be a number.</value>
      <webElementGuid>125e9709-7ca8-4501-8b98-2e53937f2944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InquiryPelunasan_SaldoEfektif</value>
      <webElementGuid>dbe477e7-e0a4-4035-b6b7-4f36a6e2ba4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InquiryPelunasan.SaldoEfektif</value>
      <webElementGuid>84ff7fa0-d633-4016-8cde-81c1d85c9585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CalculateSaldoEfektif()</value>
      <webElementGuid>177ceaf8-57f2-4f99-8eb3-0182cc217fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Saldo Efektif</value>
      <webElementGuid>a69298ca-308a-42bf-9879-a8b18c69399b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2579627d-d7b8-4b87-953c-d6c814112c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>09e0b245-b187-4d4d-b22b-39ec641dc81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InquiryPelunasan_SaldoEfektif&quot;)</value>
      <webElementGuid>475d1314-3930-4efb-8c3c-43ed6a724af3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InquiryPelunasan_SaldoEfektif']</value>
      <webElementGuid>48862198-0142-4809-8096-356fb1c551dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PenutupanRekeningForm']/div[3]/div[2]/div/input</value>
      <webElementGuid>398f7892-ef65-4262-9dfd-376a9477a4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>1e41b1c5-b39b-4eee-b126-dbabb12c24ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InquiryPelunasan_SaldoEfektif' and @name = 'InquiryPelunasan.SaldoEfektif' and @placeholder = 'Saldo Efektif' and @type = 'text']</value>
      <webElementGuid>62fd45ba-d3e8-4443-bc1a-d59365db85f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
