<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RekeningPembebananBiayaLainnya_Debet2</name>
   <tag></tag>
   <elementGuidId>e251446c-ce90-4f8e-afda-2421b1f528e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Debet2_RekeningPembebanan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Debet2_RekeningPembebanan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88f18e49-f9c2-4e76-bc5e-d896c6249e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-7</value>
      <webElementGuid>fa546d96-e895-4203-bab4-3c607fcf24ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d6f1740-c757-4221-9bd1-996fa38b8e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RekeningPembebanan field is required.</value>
      <webElementGuid>0610eeed-ae67-4438-bbf7-81bd73bedc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Debet2_RekeningPembebanan</value>
      <webElementGuid>f9ff7a23-833c-4f8d-ad21-2887690e7b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Debet2.RekeningPembebanan</value>
      <webElementGuid>1c080338-5cef-4852-b372-f1f115d1352b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rekening Pembebanan Biaya Lainnya</value>
      <webElementGuid>83de77df-245a-4563-8621-f8cad2408b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5f7f0a4-ef9d-48d0-aa60-8c11b130b8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b5e5f22a-b692-445c-ba5e-b30a218e945c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Debet2_RekeningPembebanan&quot;)</value>
      <webElementGuid>1f1a829d-0ad7-4387-8b27-ed3a551be1ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Debet2_RekeningPembebanan']</value>
      <webElementGuid>dbd545b6-7644-45b6-b38a-9d3ea58db180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PenutupanRekeningForm']/div[4]/div[2]/div/input[2]</value>
      <webElementGuid>14698f0c-6b95-4460-91fe-a8c3530e4b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[2]</value>
      <webElementGuid>202bade7-a3a9-41f5-9571-c5cb09cd8d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Debet2_RekeningPembebanan' and @name = 'Debet2.RekeningPembebanan' and @placeholder = 'Rekening Pembebanan Biaya Lainnya' and @type = 'text']</value>
      <webElementGuid>28c6b4a5-b995-4e0d-8978-ecb191432e8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
