<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NominalPembebananPokok_Debet1</name>
   <tag></tag>
   <elementGuidId>051bf75f-4ce3-4c28-841f-7af2a59f0286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Debet1_NominalPembebananPokok']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Debet1_NominalPembebananPokok</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4edb069-b1a7-4ebd-914b-69f836c364aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-7 nominal</value>
      <webElementGuid>ccfc601d-cb31-4b07-8f4a-25311669199b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6143ed7f-571b-4624-98b7-b8da77371084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field NominalPembebananPokok must be a number.</value>
      <webElementGuid>766b0b01-c036-4abb-b2ce-0b12957ce544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Debet1_NominalPembebananPokok</value>
      <webElementGuid>4e19fd03-e385-440c-9c9f-566a00132dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Debet1.NominalPembebananPokok</value>
      <webElementGuid>6544a817-f223-4ccf-a5db-6235e8bf153a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>AdjustNominalBeban(1,event)</value>
      <webElementGuid>20e0fcb0-0921-4142-840b-16dffef76355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nominal Pembebanan Pokok</value>
      <webElementGuid>0c703484-231e-4e65-8d05-424e35b40374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c98db99-0cb7-4205-ad7d-d6dead57fb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>33cfeee4-bdea-47ea-97ae-b5d0cf364141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Debet1_NominalPembebananPokok&quot;)</value>
      <webElementGuid>4fdbb88a-ab02-459c-aaf4-2235aeee5554</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Debet1_NominalPembebananPokok']</value>
      <webElementGuid>e2d35b01-eb70-44b3-8dfe-9265f2bb9583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PenutupanRekeningForm']/div[4]/div/div[8]/input</value>
      <webElementGuid>43b7dc74-a14a-4f09-95ad-028a649947eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[8]/input</value>
      <webElementGuid>791c2ec2-f9e6-42a1-8345-d018203c9f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Debet1_NominalPembebananPokok' and @name = 'Debet1.NominalPembebananPokok' and @placeholder = 'Nominal Pembebanan Pokok' and @type = 'text']</value>
      <webElementGuid>43fd0a20-0d1c-49ea-857e-67d07effe913</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
