<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NominalPembebananLainnya_Debet2</name>
   <tag></tag>
   <elementGuidId>36c82fdc-da41-47bd-91b2-5048d4f3a1cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Debet2_NominalPembebananLainnya']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Debet2_NominalPembebananLainnya</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84ebcafb-d4d1-47d5-b4ef-a75e1baa8e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-7 nominal</value>
      <webElementGuid>aff229e5-8801-474f-a508-58951db8c6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2cb481c3-9880-4a34-8dc2-b11729be1548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field NominalPembebananLainnya must be a number.</value>
      <webElementGuid>cca21117-b55b-439e-9ffa-914d9274a6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Debet2_NominalPembebananLainnya</value>
      <webElementGuid>23eb39d4-9232-4536-8e97-5e350d885f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Debet2.NominalPembebananLainnya</value>
      <webElementGuid>88549af0-32df-4bfd-ad16-6b4f60904eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>AdjustNominalBeban(2,event)</value>
      <webElementGuid>bd6d4cf3-f498-44ad-9b67-97aa975f7f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nominal Pembebanan Lainnya</value>
      <webElementGuid>c1f734fd-5475-47a5-a7b2-ca57afb901a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c9daf92b-b068-44b4-aeeb-af5d7c5800a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7641e796-d12f-4847-8c7f-0c0ad5cae941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Debet2_NominalPembebananLainnya&quot;)</value>
      <webElementGuid>f155fad7-d0ab-4ec3-be2c-5605a6c33f23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Debet2_NominalPembebananLainnya']</value>
      <webElementGuid>f5a2dd74-8852-41b9-b2b4-57ca20c65274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PenutupanRekeningForm']/div[4]/div[2]/div[8]/input</value>
      <webElementGuid>7830e96d-ff5e-4fac-8cb3-8096181c1304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[8]/input</value>
      <webElementGuid>abb25cb1-30ce-4d0a-a0ee-060ac116bbae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Debet2_NominalPembebananLainnya' and @name = 'Debet2.NominalPembebananLainnya' and @placeholder = 'Nominal Pembebanan Lainnya' and @type = 'text']</value>
      <webElementGuid>a3b26745-0bc0-445d-b76e-3531dc84c4ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
