<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RekeningPembebananSaldoPinjaman_Debet1</name>
   <tag></tag>
   <elementGuidId>1362e076-902e-4cd9-8613-bf9d9a896250</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Debet1_RekeningPembebanan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Debet1_RekeningPembebanan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aaacdb89-8e55-48a1-90c3-1a7affb78be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-7</value>
      <webElementGuid>07af121f-d4f0-4708-8620-5912815f8fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c80fd57-cf9a-462f-b216-4de328194554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RekeningPembebanan field is required.</value>
      <webElementGuid>6b88acbd-23f9-4913-97a7-3db4d127d2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Debet1_RekeningPembebanan</value>
      <webElementGuid>d074994e-78a6-420f-ad4b-8933f27f8e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Debet1.RekeningPembebanan</value>
      <webElementGuid>76046769-755f-4f99-be7f-018c13a6b1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rekening Pembebanan Saldo Pinjaman</value>
      <webElementGuid>66f93a82-7793-4c73-874a-8c084f524e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec364415-5413-42b0-b34f-a6662d63805b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>14ee8b6a-5e0a-4a88-a80a-cdb31da6b119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Debet1_RekeningPembebanan&quot;)</value>
      <webElementGuid>dc8461fe-58f5-4a58-b15d-7cecb1f0d4ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Debet1_RekeningPembebanan']</value>
      <webElementGuid>56988343-41fe-4d71-8cae-6e262c09dee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PenutupanRekeningForm']/div[4]/div/div/input</value>
      <webElementGuid>a2559bfb-45ed-4f01-b85d-c9c2b5d17d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>f7324433-d4b8-486f-93b6-3cc1d1f723c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Debet1_RekeningPembebanan' and @name = 'Debet1.RekeningPembebanan' and @placeholder = 'Rekening Pembebanan Saldo Pinjaman' and @type = 'text']</value>
      <webElementGuid>48d41365-c05a-47b4-9994-1731fd611a23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
