<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoRekeningPinjaman</name>
   <tag></tag>
   <elementGuidId>e569ddeb-0098-496d-8552-60f98b719b79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NomorRekeningPinjaman']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NomorRekeningPinjaman</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06b20c35-8ebb-4078-abbd-22d12fdc4b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>NomorRekeningPinjaman</value>
      <webElementGuid>b2c63d34-0d45-48bc-be5c-2d974b045f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NomorRekeningPinjaman</value>
      <webElementGuid>7a133ac5-ec26-4422-ba03-02471acf5d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NomorRekeningPinjaman</value>
      <webElementGuid>3b5ea1ad-baf4-4c93-a739-e0d38e22cb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-7 inputnumeric</value>
      <webElementGuid>4ad83ebb-ad14-4199-95e3-bb3173d87c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Rekening</value>
      <webElementGuid>41b93ba0-3aa7-472f-9ed3-95852066c3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>77dfaf1a-c9fe-4d57-96fc-8dd2812e0ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NomorRekeningPinjaman&quot;)</value>
      <webElementGuid>1fc2c2ff-f447-400f-891b-8091b2969085</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NomorRekeningPinjaman']</value>
      <webElementGuid>9129031e-05e7-4c46-b9f7-d0ca6fa13707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PenutupanRekeningForm']/div[3]/div/div/input</value>
      <webElementGuid>f32a3a9e-e700-4cd0-9eff-09bc84322eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>31f132a7-ea07-4959-b95b-44fa8a48602d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NomorRekeningPinjaman' and @id = 'NomorRekeningPinjaman' and @placeholder = 'Nomor Rekening']</value>
      <webElementGuid>4aa4d084-853b-4475-8540-86a55ca1828b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
