<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal Override</name>
   <tag></tag>
   <elementGuidId>1bd07f6d-562e-4142-971c-151df194ba8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Kredit_NominalOverride']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Kredit_NominalOverride</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eea7cdbf-74a3-440c-9e27-61917db8e2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-7 nominal</value>
      <webElementGuid>c24d6ccd-a9b7-44a3-a5f6-a03a2f7c10bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3294c2fe-e369-40b6-8bca-8df6deead166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field NominalOverride must be a number.</value>
      <webElementGuid>626f83ee-7bdb-47c1-b170-1bd49b39d889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kredit_NominalOverride</value>
      <webElementGuid>6343282a-8b47-4cd7-a9f2-ce50266d8b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kredit.NominalOverride</value>
      <webElementGuid>f2ff4b5a-4fb3-49e1-85f8-3d8c06722469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CheckOverrideLength()</value>
      <webElementGuid>c9b8778a-b039-44cf-a18e-616709de7065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nominal Override</value>
      <webElementGuid>ad279431-9c61-4d73-8901-d4dd260c9ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2a0074b-4d6d-4d49-87b2-ab6d081955f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5ab63fbb-b6d1-49e3-a024-e195bbf83969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kredit_NominalOverride&quot;)</value>
      <webElementGuid>c522e48b-540f-419b-9093-96d5a0ae5b59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Kredit_NominalOverride']</value>
      <webElementGuid>1db602ea-98c6-4461-9f41-0068c22c601e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overrideWrap']/input</value>
      <webElementGuid>3682855e-9940-4001-816d-57a5564944ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>e1e87206-c12a-441d-94fe-df81a92e608a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Kredit_NominalOverride' and @name = 'Kredit.NominalOverride' and @placeholder = 'Nominal Override' and @type = 'text']</value>
      <webElementGuid>c6cff7e3-caf6-48d7-8d9a-afaf16843e7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
