<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tab Result PDF</name>
   <tag></tag>
   <elementGuidId>c728e3b4-e974-45b4-8f65-cd11ccc08477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='header-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9d14f18-b60d-43eb-bd21-91a682f0c354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>29fd030c-3f75-4bb8-a08e-afb5f491ce0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-1</value>
      <webElementGuid>7a850fa7-302c-48e3-b337-78a26b5364b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>fdc1e084-14af-4335-b8ec-b56f3ccd24af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#body-1</value>
      <webElementGuid>94adb5d2-4700-4ab3-bcdb-3f01af931d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>8c5638a9-956e-46c9-a69a-6f0f94d9298a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>body-1</value>
      <webElementGuid>ea78ad44-db09-4bda-827c-54d55c692666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                              39829_48696_PinbukDana_Success.pdf
                                              
                                           </value>
      <webElementGuid>08932e08-35aa-47fb-82cd-bf58bfc6ffe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-1&quot;)</value>
      <webElementGuid>a182b841-3d7b-4ec8-ab22-b81344a1ac2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='header-1']</value>
      <webElementGuid>50edbc3f-b5f7-466f-9b36-4af1273ebbd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='headerResultTab']/li/a</value>
      <webElementGuid>995d69f3-7111-4a03-baae-25c1056bcd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'39829_48696_PinbukDana_Success.pdf')]</value>
      <webElementGuid>0688dd19-1059-4a13-acc2-e78b3ddec8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#body-1')]</value>
      <webElementGuid>42fe732c-8969-4d40-9599-f6f73b699848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a</value>
      <webElementGuid>93ac4d87-707c-48c9-8d70-884cf03692b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'header-1' and @href = '#body-1' and (text() = '&#xd;
                                              39829_48696_PinbukDana_Success.pdf&#xd;
                                              &#xd;
                                           ' or . = '&#xd;
                                              39829_48696_PinbukDana_Success.pdf&#xd;
                                              &#xd;
                                           ')]</value>
      <webElementGuid>265bcac2-d08d-47cc-aadf-c860de284c28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
