<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Approval_View</name>
   <tag></tag>
   <elementGuidId>f17433d8-9cbb-4b6f-b2e6-ce13e3dd9b11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='activityTable']/tbody/tr/td[5]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Edit' and (text() = '
                             View
                            ' or . = '
                             View
                            ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-outline-dark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f2f57c03-6f1d-47b3-a446-27fd61fee478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activityid</name>
      <type>Main</type>
      <value>10458</value>
      <webElementGuid>e7fb59b0-ec5d-44f4-a352-48bfb4c6a547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-dark</value>
      <webElementGuid>c6b5a980-8b44-461c-b52c-87a39fc3a67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>c1c65b7f-a5c6-4ebf-bf50-98a8aa6fbabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>bdffb4e7-05bb-4276-84e4-63fbfd0d2133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>767486bb-a12f-47a1-8440-65c8600b056d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             View
                            </value>
      <webElementGuid>19e929d6-367a-40a4-a0b7-f0359c3b5c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;activityTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[5]/button[@class=&quot;btn btn-outline-dark&quot;]</value>
      <webElementGuid>154a70f6-e7d4-4d06-9fc8-1f84eb3ba02c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='activityTable']/tbody/tr/td[5]/button</value>
      <webElementGuid>eb5d9422-b5b0-446a-87db-909dbc09b5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>96ab2218-d291-4036-b353-27a82858d44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Edit' and (text() = '&#xd;
                             View&#xd;
                            ' or . = '&#xd;
                             View&#xd;
                            ')]</value>
      <webElementGuid>e270cf3c-e0bd-412f-8211-79d65d3586c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
