<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Approve_or_Reject</name>
   <tag></tag>
   <elementGuidId>f84683c1-6ddd-45c1-8b7b-87889747e9b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Action']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'Action' and @id = 'Action']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Action</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cc313c39-eaf9-4237-8e98-0eadd2a1d118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-12</value>
      <webElementGuid>a3e0529e-8fca-48e6-b9ca-99310b0cca31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Action</value>
      <webElementGuid>0b398838-1b2c-4871-9847-17fafb411b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Action</value>
      <webElementGuid>ee9ff93f-02ee-4ba2-99fa-66711efda1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Action&quot;)</value>
      <webElementGuid>dab39137-e596-49e6-8f2a-0082332c47c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Action']</value>
      <webElementGuid>b874d2ba-af35-46dd-a752-d1326f7823ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-tabs-one-tabContent']/div[3]/div/select</value>
      <webElementGuid>d0e78826-f706-48d0-9c75-65af97c0ca23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>cc967197-d900-4bc4-8269-dfc9132ea90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Action' and @id = 'Action']</value>
      <webElementGuid>59908a7c-6665-403e-95a0-40f3f6775143</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
