<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalPKAkhir</name>
   <tag></tag>
   <elementGuidId>e456af39-615a-4685-add4-9dc0d293f83d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DetailRateBunga_TanggalPKAkhir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DetailRateBunga_TanggalPKAkhir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a68c647b-e7fb-47dc-b919-d4dfc8aca16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>461cad5d-bf0f-485f-9149-ae6eece2c758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#tanggalPkAkhirDate</value>
      <webElementGuid>f846b36e-23a5-4307-b010-edc32cf27365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DetailRateBunga_TanggalPKAkhir</value>
      <webElementGuid>f3198abc-f2b6-4e00-b519-173697c0fa7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DetailRateBunga.TanggalPKAkhir</value>
      <webElementGuid>e359c679-af21-474b-bb64-493eefa794c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>5264601d-7a63-4f4a-8be1-8a3329f78786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82c71ee8-7d9a-4fe7-997f-63578050215a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fcfd3154-6394-43dc-912e-14b99879be85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DetailRateBunga_TanggalPKAkhir&quot;)</value>
      <webElementGuid>51e799b2-e662-4eeb-94dd-0e34fd948a12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DetailRateBunga_TanggalPKAkhir']</value>
      <webElementGuid>fadc586b-e252-4449-b115-02abad5cb5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tanggalPkAkhirDate']/input</value>
      <webElementGuid>c7ad1cfd-d4e0-4424-bdbd-a64c149439d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a6f2571b-8616-4a07-a9ec-24bbef577e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DetailRateBunga_TanggalPKAkhir' and @name = 'DetailRateBunga.TanggalPKAkhir' and @placeholder = 'dd/mm/yyyy' and @type = 'text']</value>
      <webElementGuid>6e46281d-66b6-44c0-9c04-17cf6cee1107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
