<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalPKAwal</name>
   <tag></tag>
   <elementGuidId>cc0e85e8-e5db-41f4-b8d3-e95b7bed36b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DetailRateBunga_TanggalPKAwal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DetailRateBunga_TanggalPKAwal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c23e9f7-70a7-41b5-987b-c967e4b8a6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>47d79ef2-c313-450b-b221-66762f136408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#tanggalPkAwalDate</value>
      <webElementGuid>899001fa-90a2-4f0d-bfed-7353a77a967b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DetailRateBunga_TanggalPKAwal</value>
      <webElementGuid>37e1e1d0-8898-4da1-beab-71616b76b071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DetailRateBunga.TanggalPKAwal</value>
      <webElementGuid>925b744c-b663-4556-91f0-0582a5896be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>daf514d7-085d-4ccc-94e5-d9d7260fb26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4ace2f8-0217-4d2b-abfc-7b4c2aa5388b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>14ced918-854f-4f01-a225-2ea34a1c6814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DetailRateBunga_TanggalPKAwal&quot;)</value>
      <webElementGuid>8a51dce7-ba23-4abb-b9e0-da092af45b5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DetailRateBunga_TanggalPKAwal']</value>
      <webElementGuid>e6dabaaa-8e42-446f-b772-1e326802cc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tanggalPkAwalDate']/input</value>
      <webElementGuid>60ec714f-5a10-41c9-b2d6-5ff7d3d57bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>324174b1-7820-4038-b76f-9540919b4e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DetailRateBunga_TanggalPKAwal' and @name = 'DetailRateBunga.TanggalPKAwal' and @placeholder = 'dd/mm/yyyy' and @type = 'text']</value>
      <webElementGuid>342f2695-7d51-496f-8471-534e711b8f52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
