<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_StatusActivity</name>
   <tag></tag>
   <elementGuidId>91ef5c63-42d7-43eb-9e56-b068f78d6f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='activityTable']/tbody/tr/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9396e49b-1b73-452c-a3f5-2053ae3dd3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approved </value>
      <webElementGuid>cf5d4016-8a0b-480d-8455-d3858b9ff70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;activityTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[4]</value>
      <webElementGuid>0e8cb4de-fca0-4f96-9848-c434b600b82f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='activityTable']/tbody/tr/td[4]</value>
      <webElementGuid>d7dcf266-b468-491b-a7fa-e2d0e4d109fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]</value>
      <webElementGuid>0ab0df83-f46f-437a-a874-8197e21e2a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Approved ' or . = 'Approved ')]</value>
      <webElementGuid>39bd2b11-4158-46ee-9240-514c91a1866e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
