<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pokok</name>
   <tag></tag>
   <elementGuidId>264a3b68-4f87-42df-9319-47cd6db24268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AdjustValue_Pokok']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AdjustValue_Pokok</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05e71503-df06-4038-a78b-2c0722063d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>24a83543-2832-4a0a-a0a8-9a5e0e7d6050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>66139911-ae7f-4f55-af44-438454518558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Pokok must be a number.</value>
      <webElementGuid>92c2d8e2-a4af-4166-ad73-6b87422fdebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AdjustValue_Pokok</value>
      <webElementGuid>90ee7a09-11a5-4a60-a11a-b1d48e542784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AdjustValue.Pokok</value>
      <webElementGuid>78b493aa-5900-4e47-be3c-bc674f0ee470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>calculateResult('Pokok')</value>
      <webElementGuid>72cb5075-adc7-433a-811c-cc124982775d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c07275c7-0a88-4ca9-b9c4-95bd68cef008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1f376923-3e61-4441-ac8a-ad0cd2966864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AdjustValue_Pokok&quot;)</value>
      <webElementGuid>9561ea78-00fc-42ec-9c1a-f5116e8f2ed1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AdjustValue_Pokok']</value>
      <webElementGuid>0587c58a-c3a8-4392-8acc-aa6d4afac47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormBucket']/table[2]/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>12dfd221-010e-4e62-abf8-d2d95a9632ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>a36fa6aa-2acb-4fee-a84b-fbe50dbe02b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AdjustValue_Pokok' and @name = 'AdjustValue.Pokok' and @type = 'text']</value>
      <webElementGuid>d4555da2-a498-4425-bdb7-4972f7e6b000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
