<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KodeStruk</name>
   <tag></tag>
   <elementGuidId>b715c705-c1e4-4f04-9e86-1dbfcb4ccd42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#KodeStruk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='KodeStruk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6399c8c-f9b0-42d6-abbf-c631e9a53e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3a0388cf-d85e-4498-b063-f3656b90a15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c1071916-2338-4767-ad41-478b985bfb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The KodeStruk field is required.</value>
      <webElementGuid>2711f93c-94a4-4649-bad4-48afaa02ae40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>KodeStruk</value>
      <webElementGuid>28aa681b-38ee-4d09-b6d1-fa0fa943c638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>KodeStruk</value>
      <webElementGuid>e70b2af4-1b11-4b4c-ba6c-9b45c01c3fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>f76b4304-b389-4461-b8b2-c64610fad427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d2d960f-ec53-4bb6-86d6-3dfb68d653a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e30c1a12-f3c6-4253-9f05-e27d2651275a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;KodeStruk&quot;)</value>
      <webElementGuid>504f1b7c-6a00-479d-984d-31087355e098</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='KodeStruk']</value>
      <webElementGuid>3f3409b4-24b9-47b0-a617-39b21843617d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormBucket']/table/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>d571ac6f-0061-4d1f-8100-0ecb3eb3c66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/input</value>
      <webElementGuid>5eebf438-4328-4590-ad36-54d73a20e779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'KodeStruk' and @name = 'KodeStruk' and @type = 'text']</value>
      <webElementGuid>4480eabf-9e85-461d-8379-331e7ab33774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
