<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NorekSingleSide_pokok</name>
   <tag></tag>
   <elementGuidId>b991448e-7e24-4394-92de-5f8b994110ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NorekSingleSidePokok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NorekSingleSidePokok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75268db1-bab8-4fec-9245-e4326f4d717d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>555a5ece-6bd1-4df4-8734-7adc277a61ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ea936def-f869-40d0-8897-b6d03ebae5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NorekSingleSidePokok field is required.</value>
      <webElementGuid>24de2ec9-feef-4639-91d5-9df1d05e54f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NorekSingleSidePokok</value>
      <webElementGuid>cb78af0f-c897-4d7c-9165-5d50d0900926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NorekSingleSidePokok</value>
      <webElementGuid>facd97f5-740f-4159-9f4f-551f9dae673e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SingleSide Pokok</value>
      <webElementGuid>593068f3-9be6-4be2-b529-68983e700c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f20db19c-acbe-4156-93bb-7c133319dc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0cf4ce3f-187e-41c8-bd44-953d20a3ecfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>045be6f1-67a5-4c7c-a28d-105ac0195d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NorekSingleSidePokok&quot;)</value>
      <webElementGuid>3f404373-307e-4cae-bed2-83924299c254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NorekSingleSidePokok']</value>
      <webElementGuid>922ef5ff-2528-415d-ba48-b9454038c7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormBucket']/table[2]/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>bb13abf0-e3f4-40ac-a47d-158e5ada8d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>feecdac0-ae57-4c22-9b20-8c60ab1572bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NorekSingleSidePokok' and @name = 'NorekSingleSidePokok' and @placeholder = 'SingleSide Pokok' and @type = 'text']</value>
      <webElementGuid>10bc54f3-4f2b-4cb8-85a6-de3df4cfce29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
