<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bunga</name>
   <tag></tag>
   <elementGuidId>0cc7c3dd-acdd-4582-b81e-07c7aa9b8176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AdjustValue_Bunga']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AdjustValue_Bunga</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb378b4f-ba96-41e8-9dd0-9433b900925e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>91858908-7a2a-43b0-abe4-a689ff6cb71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3980c47-8e3e-4952-b6b0-521a7d9727a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Bunga must be a number.</value>
      <webElementGuid>20a5599d-d9cc-420e-bda2-41bd5d5b0986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AdjustValue_Bunga</value>
      <webElementGuid>ea751376-8c9e-4683-81dc-5a7a041ab881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AdjustValue.Bunga</value>
      <webElementGuid>b0b0cc14-6fce-47b6-b347-e6110d3b5584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>calculateResult('Bunga')</value>
      <webElementGuid>b5f1e98c-b7b9-4913-bc31-9d53c3f6d28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fc8ded9-6ba9-431a-9cad-e290eff13c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>feb71ce1-27dd-4cb6-9014-94aebe98b1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AdjustValue_Bunga&quot;)</value>
      <webElementGuid>97f7973b-6840-4602-8032-3ebf7f776db7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AdjustValue_Bunga']</value>
      <webElementGuid>0af1f5e1-8c72-408d-b256-f464b2ab7bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormBucket']/table[2]/tbody/tr[3]/td[3]/input</value>
      <webElementGuid>a1267496-c8ef-40d7-8d8f-030049a62ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/input</value>
      <webElementGuid>bbf282ad-2cc9-4a38-803d-8ebc991c9905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AdjustValue_Bunga' and @name = 'AdjustValue.Bunga' and @type = 'text']</value>
      <webElementGuid>11522db3-323e-402f-a6e5-ffd26a01085a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
