<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Biaya</name>
   <tag></tag>
   <elementGuidId>bf03c1a2-d53d-4c0d-acdd-cc7a0b14d9ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AdjustValue_Biaya']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AdjustValue_Biaya</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e00bfcb-906b-47cb-8822-4bede785bb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4c4e5065-baa8-4f68-a48f-0992a018e976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>84a6de2f-f4b3-4d90-b88c-dda09fa8a21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Biaya must be a number.</value>
      <webElementGuid>3efb438c-dccf-4a08-8405-bdaf7a1b56c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AdjustValue_Biaya</value>
      <webElementGuid>263a1b6f-dc0a-4b44-91df-f1263a60f9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AdjustValue.Biaya</value>
      <webElementGuid>59f09a69-f2cb-436f-b2e9-637cb8f34862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>calculateResult('Biaya')</value>
      <webElementGuid>328aafae-ecd4-49f7-913e-5cab7701aba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b285187-0e8d-4369-a1ea-15331c0e0a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2f14a532-e718-4a3a-9ac4-04435b172fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AdjustValue_Biaya&quot;)</value>
      <webElementGuid>83656948-c7a1-4e4a-81a2-be17834a7bed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AdjustValue_Biaya']</value>
      <webElementGuid>4415ba62-6ed4-44a5-aa39-5834c4ff47aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormBucket']/table[2]/tbody/tr[4]/td[3]/input</value>
      <webElementGuid>1fe11da7-1d70-4c36-b715-e3e96538610d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/input</value>
      <webElementGuid>83c71ad1-1553-4fa1-83e0-90ecbd408d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AdjustValue_Biaya' and @name = 'AdjustValue.Biaya' and @type = 'text']</value>
      <webElementGuid>bc5d0302-c8b7-48b9-93bf-ff6efe8a6dcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
