<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WorstCollectibility</name>
   <tag></tag>
   <elementGuidId>6b9a87c4-7a43-4260-8ae8-ac46f839b433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WorstCollectibility</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WorstCollectibility']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86a30362-487b-463c-be83-63c701593de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ba8a5969-8492-4e48-9b33-5a9ac6911987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0b2e2344-cb19-49a4-bd52-012d3525a2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The WorstCollectibility field is required.</value>
      <webElementGuid>e8686780-a085-4d7c-8acf-8e43725fc730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WorstCollectibility</value>
      <webElementGuid>63b82540-1fa5-47fd-b5c9-0880cc13c713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WorstCollectibility</value>
      <webElementGuid>a2bbf003-0546-43bb-8616-293e21e711f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>d4acb83d-cc4a-4a02-aba3-595f633ffabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec95cb09-4674-4fb1-93d3-059d7ce1e198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>01:PASS</value>
      <webElementGuid>941412a1-5405-449b-a18e-c9f2829a4f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4ed8df93-e44b-481a-bba4-c8475e0e92a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WorstCollectibility&quot;)</value>
      <webElementGuid>15c24d4c-b987-474f-9f97-bb9c601c07e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WorstCollectibility']</value>
      <webElementGuid>40e5d8e5-6c53-478e-b8af-24fc07b6d206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormBucket']/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>cc6e63cf-bb42-4f2f-af19-45aa5c648aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>525661f2-3f28-435f-8128-41c5dc89493f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'WorstCollectibility' and @name = 'WorstCollectibility' and @type = 'text']</value>
      <webElementGuid>bd603fd7-3aa3-411e-bb23-8c122f95aca8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
