<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NorekSingleSide_biaya</name>
   <tag></tag>
   <elementGuidId>1bea50c3-36bb-417d-b293-ed93147b0d8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NorekSingleSideBiaya</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NorekSingleSideBiaya']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>598ceffc-bb63-4d8b-b058-25a3e986738d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7b0fdfd5-9528-4a0e-90ea-5ecdc9086455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1ecb3273-eddb-4e97-b666-4e449bb5aef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NorekSingleSideBiaya field is required.</value>
      <webElementGuid>8aa6263d-eff2-471c-99ad-a0194b53b077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NorekSingleSideBiaya</value>
      <webElementGuid>3d5689d0-4628-47ea-9fad-e9920e40fe29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NorekSingleSideBiaya</value>
      <webElementGuid>d87f115c-cc76-4b01-9c3c-c7e187d84c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SingleSide Biaya</value>
      <webElementGuid>f0b67f94-d886-416e-a8da-2f6784971417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>8f05f9f2-9875-4697-9198-7d73c74ea49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d707cb2-16a2-4386-acfb-f43c40fe4916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dade2e15-e48e-4f61-8dcb-e63c07ffb2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NorekSingleSideBiaya&quot;)</value>
      <webElementGuid>5a7cc7f8-4804-4747-b1c7-a0a9d3b2dc3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NorekSingleSideBiaya']</value>
      <webElementGuid>d63693f5-e2e2-4690-ab9b-e01c26576e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormBucket']/table[2]/tbody/tr[4]/td[5]/input</value>
      <webElementGuid>cc1c7bbe-4f94-4fb7-a55b-2c088d031114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/input</value>
      <webElementGuid>d2e84042-5566-49c2-bf52-0aace3aab3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NorekSingleSideBiaya' and @name = 'NorekSingleSideBiaya' and @placeholder = 'SingleSide Biaya' and @type = 'text']</value>
      <webElementGuid>50042095-b514-4465-8d21-6d678565ff0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
