<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Teoritis</name>
   <tag></tag>
   <elementGuidId>7ee78835-8eef-499c-b997-ce85bd1ba1a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AdjustValue_Teoritis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AdjustValue_Teoritis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>339f2d26-7faa-434a-92c6-4fecc9b64a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>653c3ebc-8033-4c20-92d7-4d9b01355384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ced054f2-b711-4a43-85d8-1cae09fdc84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Teoritis must be a number.</value>
      <webElementGuid>585c987e-0d9d-4bae-96be-66c166b65577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AdjustValue_Teoritis</value>
      <webElementGuid>8dfc92f9-3108-47ea-87a4-7f329f438052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AdjustValue.Teoritis</value>
      <webElementGuid>648a2caf-04f7-4784-a1ec-67801c5a0e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>calculateResult('Teoritis')</value>
      <webElementGuid>8a65422f-4728-489c-b46c-846b6a139a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ccd6c0d4-d1d1-4aca-b492-8313492f1b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>64f23175-dfa9-4358-88ec-955802d9eae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AdjustValue_Teoritis&quot;)</value>
      <webElementGuid>1be207ac-2eb4-44cb-82f5-28405be6b2f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AdjustValue_Teoritis']</value>
      <webElementGuid>e2f1ce21-be7a-42f6-897f-8e37e58794e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormBucket']/table[2]/tbody/tr[6]/td[3]/input</value>
      <webElementGuid>7e067ca7-c443-4e8c-9c1c-cd69095df68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[3]/input</value>
      <webElementGuid>f2161c47-0ce7-4885-a1d8-3c13ad268b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AdjustValue_Teoritis' and @name = 'AdjustValue.Teoritis' and @type = 'text']</value>
      <webElementGuid>da5e7fe1-0803-4693-babf-7ec7b7a80f9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
