<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NomorRekening</name>
   <tag></tag>
   <elementGuidId>4e582db4-c121-413a-9aff-0c7b69d687f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NomorRekening']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NomorRekening</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6227f3a4-bb04-4f3a-a775-d1c6eefe4451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>NomorRekening</value>
      <webElementGuid>8beee493-ff95-4b52-8aa9-6a0d584c3e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NomorRekening</value>
      <webElementGuid>18b13877-d6d9-4a0d-a9ff-1d256ce3a627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NomorRekening</value>
      <webElementGuid>e6248392-c086-48f8-9db4-2e5158ee8a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-6 inputnumeric</value>
      <webElementGuid>1a7812f1-72b4-4d58-8dd2-d17bb1173b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Rekening</value>
      <webElementGuid>5f420bef-d0cc-496b-887f-055ae2dea700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7220ab48-bb8b-47ad-a28c-89667b8c863b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NomorRekening&quot;)</value>
      <webElementGuid>19d7c0f0-5a20-465d-8ea1-4e216b2d74e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NomorRekening']</value>
      <webElementGuid>6e0091dc-5264-4bd4-b498-f61648fba869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='BlokirRekeningForm']/div[3]/input</value>
      <webElementGuid>7e305ef7-cebe-4361-ac54-6da54caf8595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>04f2b11e-1f72-471b-8ef3-bae24f128a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NomorRekening' and @id = 'NomorRekening' and @placeholder = 'Nomor Rekening']</value>
      <webElementGuid>b1a70435-7581-4232-b80f-9d5908f84e33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
