<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PasangOrLepas_PendingRek</name>
   <tag></tag>
   <elementGuidId>636a73a8-893c-433b-a01c-736760c0368c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='listPerlakuan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#listPerlakuan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3a707c65-0188-4278-b246-b206acc00ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-control col-md-6</value>
      <webElementGuid>c5402938-1d20-438c-836f-5967964d86b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>Perlakuan</value>
      <webElementGuid>822ccf41-4afc-403e-b3ef-0f3228d9589a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Perlakuan</value>
      <webElementGuid>5bb507e8-0787-4811-bf78-596ce7a6f1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>listPerlakuan</value>
      <webElementGuid>a8aa0de6-45a5-408f-b5ef-7d2913a4d1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            --- Pilih Opsi ---
                            Pasang
                            Lepas
                        </value>
      <webElementGuid>ebba65cd-8d65-4f67-8574-4377039888e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listPerlakuan&quot;)</value>
      <webElementGuid>b1b42592-41dd-4748-b25b-10a735c7696a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='listPerlakuan']</value>
      <webElementGuid>1eaa17c7-ba79-42a6-894e-6088eab7f859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PendingRekeningForm']/div[6]/select</value>
      <webElementGuid>468f9180-7e95-4288-a5ee-ac71959e7068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>10f0e4f4-77b1-47c5-9ddc-288a131fc060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Perlakuan' and @id = 'listPerlakuan' and (text() = '
                            --- Pilih Opsi ---
                            Pasang
                            Lepas
                        ' or . = '
                            --- Pilih Opsi ---
                            Pasang
                            Lepas
                        ')]</value>
      <webElementGuid>f8d3c311-c5fd-4675-beb9-3812e00e7f97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
