<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rek. Pembebanan Biaya</name>
   <tag></tag>
   <elementGuidId>2b25a076-917a-4b60-8790-c52df29c1c07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Asuransi_Pembebanan_NoRekening']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Asuransi_Pembebanan_NoRekening</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c55db161-708f-4cad-862c-b17cd999938f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dca0184e-2352-4132-aa53-a35ccea3a0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>873ad818-9fd3-4681-a0ac-50b14cac3641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NoRekening field is required.</value>
      <webElementGuid>e84158a2-9a38-468c-abd4-34a9304558c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Asuransi_Pembebanan_NoRekening</value>
      <webElementGuid>90315923-9468-4265-9507-e69786768d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Asuransi_Pembebanan.NoRekening</value>
      <webElementGuid>e3478dd1-d6cd-4a45-81f9-6980e569bfde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>copyRekPembebananBiaya()</value>
      <webElementGuid>dce2272d-0666-4a20-913c-778b0a55d80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5168b141-5ccc-43e6-a5ef-3f7773d2ebca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>57ded715-e7fd-4541-88a7-b358fe0c2617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Asuransi_Pembebanan_NoRekening&quot;)</value>
      <webElementGuid>263b41b7-2eb8-4f7c-af57-33fd017630eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Asuransi_Pembebanan_NoRekening']</value>
      <webElementGuid>7b2c1a78-9394-472c-8600-82d7c9dc90f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormAsuransi']/div/div[5]/div[3]/input</value>
      <webElementGuid>61402544-bb1b-4db1-b06e-f0360af66933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>84fa900a-823a-42ef-ae45-0b0d08280531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Asuransi_Pembebanan_NoRekening' and @name = 'Asuransi_Pembebanan.NoRekening' and @type = 'text']</value>
      <webElementGuid>1631c555-cf3a-4793-a5d8-fe61f0b2f4f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
