<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Biaya Materai</name>
   <tag></tag>
   <elementGuidId>27fcc146-2262-42ff-ad20-506932b27f50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Asuransi_Detail_BiayaMaterai']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Asuransi_Detail_BiayaMaterai</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fd16e39-c715-4c91-acad-8022d291a187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control money-tag</value>
      <webElementGuid>946be6a9-bfe3-4b2f-ae65-20a3e0b03bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d166d265-511b-4255-b68f-877c50113571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field BiayaMaterai must be a number.</value>
      <webElementGuid>64d1317b-066f-4e20-83e3-97bbb2be7ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Asuransi_Detail_BiayaMaterai</value>
      <webElementGuid>0a68551b-c7cb-4cc4-b007-84f1358d77b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Asuransi_Detail.BiayaMaterai</value>
      <webElementGuid>a0a3e866-d88b-4fb5-8b1e-3282ec0ebb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>calculateTotalPremi()</value>
      <webElementGuid>6cbf0a52-e373-4836-b968-fc6f05385bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>524b334b-8dff-466c-bf49-b274dd04ac9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9c054a25-1f02-4bc0-bcae-8ee1bc2b5790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Asuransi_Detail_BiayaMaterai&quot;)</value>
      <webElementGuid>9cb13a68-34e1-4ad1-9f1b-aceb5a3a5583</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Asuransi_Detail_BiayaMaterai']</value>
      <webElementGuid>838f666f-1df9-41a9-8cbb-0135283734f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormAsuransi']/div/div[5]/div/input[11]</value>
      <webElementGuid>9cd0707f-03b1-4056-ba70-adc06cf6c406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[11]</value>
      <webElementGuid>f3e8a09c-de85-44f9-8b0d-f2ec0d9b9ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Asuransi_Detail_BiayaMaterai' and @name = 'Asuransi_Detail.BiayaMaterai' and @type = 'text']</value>
      <webElementGuid>97269cfb-8318-4a35-b343-2a41a101f096</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
