<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Biaya Polis</name>
   <tag></tag>
   <elementGuidId>8eb1ef3a-8ef4-4a50-9570-d7830e2a916a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Asuransi_Detail_BiayaPolis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Asuransi_Detail_BiayaPolis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39e88436-26a4-479d-baca-a347217bbd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control money-tag</value>
      <webElementGuid>1191285b-174b-4e55-bef5-57a405d98747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a0e1eb57-3de8-41f2-b740-5631d437fb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field BiayaPolis must be a number.</value>
      <webElementGuid>ef6447a5-cc1e-46c9-ac2b-657ef3fa7cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Asuransi_Detail_BiayaPolis</value>
      <webElementGuid>e1b10580-1726-4921-806d-1c69f1fef210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Asuransi_Detail.BiayaPolis</value>
      <webElementGuid>cd3e858c-6267-41f3-9cbc-43ce45e79c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>calculateTotalPremi()</value>
      <webElementGuid>8665bbce-5f1e-4805-b708-10072cf082dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b71e12fc-aeaf-49f8-ae6e-a50bdc7c6160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7365c37c-9d2b-437a-af06-1d1e7e38877b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Asuransi_Detail_BiayaPolis&quot;)</value>
      <webElementGuid>aeb465a7-5dca-4eab-aa84-7f89e1a40a45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Asuransi_Detail_BiayaPolis']</value>
      <webElementGuid>87d30e82-e05e-4d50-aca6-ddbebba6dce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormAsuransi']/div/div[5]/div/input[10]</value>
      <webElementGuid>42ac0209-a69c-4150-af8b-b6370f636dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[10]</value>
      <webElementGuid>1401d1fc-c975-4aee-a645-8574116f0455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Asuransi_Detail_BiayaPolis' and @name = 'Asuransi_Detail.BiayaPolis' and @type = 'text']</value>
      <webElementGuid>514d4079-6252-495f-9dce-4da64b9f7297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
