<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal Premi</name>
   <tag></tag>
   <elementGuidId>787a77da-8243-41b6-be5b-157ff78c874b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Asuransi_Detail_NominalPremi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Asuransi_Detail_NominalPremi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c295db73-062c-4a6b-8cb7-2d305b67a98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control money-tag</value>
      <webElementGuid>69f8f0bf-3a8b-448c-8a14-8f2c2fab59f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>75b7dcb7-0473-4bc2-89b0-bad6fe3dc660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field NominalPremi must be a number.</value>
      <webElementGuid>d40cd2d4-f01a-4760-ad57-b5d471953540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Asuransi_Detail_NominalPremi</value>
      <webElementGuid>59f49f27-21d5-4b63-b0d7-c0c5fc6fe200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Asuransi_Detail.NominalPremi</value>
      <webElementGuid>80ee9599-2468-4ed5-9ff7-66cd55ec7c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>calculateImbalJasa()</value>
      <webElementGuid>6ed9ce21-7ceb-4768-85c6-742ae450e040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0cb2a7f1-4e87-4950-924a-e7900324d236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>94a7dc08-fda5-4e34-b248-4b416fd0b015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Asuransi_Detail_NominalPremi&quot;)</value>
      <webElementGuid>35c10d9e-c90a-4259-a5f5-16c06a41d423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Asuransi_Detail_NominalPremi']</value>
      <webElementGuid>e34bd375-b5a0-46b3-ae1c-36507e38876c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormAsuransi']/div/div[5]/div/input[8]</value>
      <webElementGuid>10d63dd7-adc6-42da-909f-228f71cf4f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[8]</value>
      <webElementGuid>da9556e7-4ea8-4310-b012-0a3cc817e19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Asuransi_Detail_NominalPremi' and @name = 'Asuransi_Detail.NominalPremi' and @type = 'text']</value>
      <webElementGuid>1fc37968-79a1-4e64-b15f-a419c44cf861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
