<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Polis</name>
   <tag></tag>
   <elementGuidId>b6864e50-637c-48b3-8283-d4c8ccd4fc37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Asuransi_Detail_NoPolis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Asuransi_Detail_NoPolis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1b45c52-18dc-43dc-a1f9-5e968f53d21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>45cd181f-c137-444e-b42e-2e1ccde0904a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c025fa00-216b-4fec-93f5-9a262f99ad56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NoPolis field is required.</value>
      <webElementGuid>f458b0d9-b28b-4e89-946b-54d6a6c5b053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Asuransi_Detail_NoPolis</value>
      <webElementGuid>d0754b0c-bf5f-440d-8d11-84a3dde67719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>fb7e58d3-4a5c-4215-ae79-3ad4eef9592a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Asuransi_Detail.NoPolis</value>
      <webElementGuid>78e9fabe-ce31-4c26-b2ad-cffe4c3dda8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>fillKeteranganPinbuk();checkNoPolisLength()</value>
      <webElementGuid>7e03bbbb-a82e-4bb9-900a-a170cf82565d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df1f30be-f755-4413-8cca-052c3dee2436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f038faaa-17a3-407e-b41e-1614c08bd4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Asuransi_Detail_NoPolis&quot;)</value>
      <webElementGuid>9a9e7b97-8eee-41d7-ab17-9ec12f21960a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Asuransi_Detail_NoPolis']</value>
      <webElementGuid>1787e1a9-69d1-483f-b5d9-2f360e6d82c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormAsuransi']/div/div[5]/div[2]/input[3]</value>
      <webElementGuid>29fa80c2-f690-405b-b259-34f318753ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[3]</value>
      <webElementGuid>d10962b7-d666-4cac-9f05-31d0c03fbde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Asuransi_Detail_NoPolis' and @name = 'Asuransi_Detail.NoPolis' and @type = 'text']</value>
      <webElementGuid>7b033ad2-55cc-4834-86dc-88617646c27e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
