<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rek. Perusahaan Asuransi</name>
   <tag></tag>
   <elementGuidId>0634f9e6-66ca-4cf3-95e6-40be4150418b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RekPerusahaanAsuransi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RekPerusahaanAsuransi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79310fd6-a70f-40f3-b98d-2bb17cf5a56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8caa551b-9e0e-4b78-9e2a-4bd62218facc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ccc10ae1-187e-4cf8-94d6-46e6a08e8d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RekPerusahaanAsuransi field is required.</value>
      <webElementGuid>a827e0b0-2900-4353-90ea-5691eb4492e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RekPerusahaanAsuransi</value>
      <webElementGuid>a7238a51-9cbe-45c4-a810-11b567717cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RekPerusahaanAsuransi</value>
      <webElementGuid>451d8c2b-fdbe-4406-ab93-0d4b1a35f72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71b02ad1-da2d-4f84-880a-4bbc7f33369f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>52917bf4-80e3-4def-9419-92fa3ddc1baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RekPerusahaanAsuransi&quot;)</value>
      <webElementGuid>ea4bb4f6-1d60-47fb-8c45-f403fa05f2fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RekPerusahaanAsuransi']</value>
      <webElementGuid>3b05e9e5-debc-4a86-b465-63202f35e28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormAsuransi']/div/div[5]/div[2]/input</value>
      <webElementGuid>b4d161cb-f26a-4629-ab8f-db00b6ca3856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>bf8eec9b-7acc-4d4c-9a9d-db7a37e0d4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'RekPerusahaanAsuransi' and @name = 'RekPerusahaanAsuransi' and @type = 'text']</value>
      <webElementGuid>85154852-a477-49ab-b1e6-d26ba1b50f22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
