<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Jatuh Tempo</name>
   <tag></tag>
   <elementGuidId>9f546e77-01d0-4cc0-a05e-df10526c20c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Asuransi_Detail_TanggalJatuhTempo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Asuransi_Detail_TanggalJatuhTempo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f0e29a3-9b2c-4625-afa3-b693d576c582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa11ecba-fa43-4c11-ab1c-29512b5b000e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>70aef066-ecfa-477f-af84-55d2443b326c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Asuransi_Detail_TanggalJatuhTempo</value>
      <webElementGuid>d519fca4-32da-4e7d-9046-e66e72a67f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateJatuhTempo()</value>
      <webElementGuid>7368e3ec-2348-4a20-83e6-cd948347b99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Asuransi_Detail.TanggalJatuhTempo</value>
      <webElementGuid>72bb401a-79b6-429d-b86a-bd203a4eeecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#tanggalJatuhTempo</value>
      <webElementGuid>f55f15a0-85c3-48d1-a5ff-d24d16f20e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fd7469ab-6a43-47d8-993e-e75f676e0996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Asuransi_Detail_TanggalJatuhTempo&quot;)</value>
      <webElementGuid>3d0df862-555a-4e87-acdc-094d2e19f3d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Asuransi_Detail_TanggalJatuhTempo']</value>
      <webElementGuid>f0bf4761-a0ab-4af7-a12f-88bd385936b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tanggalJatuhTempo']/input</value>
      <webElementGuid>116fbbad-a515-4fe6-9a64-902f532f2ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>c6933728-0efb-4a86-8761-2c1f0f3fd407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Asuransi_Detail_TanggalJatuhTempo' and @name = 'Asuransi_Detail.TanggalJatuhTempo']</value>
      <webElementGuid>488d505a-d839-453c-9563-62fd82029f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
