<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Jenis Rek Pembebanan Biaya</name>
   <tag></tag>
   <elementGuidId>f3ebcb53-ddee-4142-8417-a0e3b059c453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Asuransi_Pembebanan_Jenis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Asuransi_Pembebanan_Jenis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>034e049d-372e-4b88-89a4-8817e5fc6e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2f3ab205-ce08-41af-b04d-e6a0b688194e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Asuransi_Pembebanan.Jenis</value>
      <webElementGuid>74d61500-0937-4e83-a154-64a5f32709ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Asuransi_Pembebanan_Jenis</value>
      <webElementGuid>7b17461d-a7e8-44fb-95b5-dc90b10ddd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>jenisChanged()</value>
      <webElementGuid>6bf8b86c-aec0-4562-b3bb-503317a39a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Simpanan
                                Pinjaman
                            </value>
      <webElementGuid>079e1f33-be5f-4379-9dc6-b0de26c6c0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Asuransi_Pembebanan_Jenis&quot;)</value>
      <webElementGuid>b37024d3-8443-4225-8332-4d0411a3580b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Asuransi_Pembebanan_Jenis']</value>
      <webElementGuid>363aaed2-3e42-4b3f-ad75-052905ff4d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormAsuransi']/div/div[5]/div[3]/select</value>
      <webElementGuid>97b20469-aece-4740-aef2-43780aa59259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>b03f2bf4-b4fb-4712-a014-7a60152baf24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Asuransi_Pembebanan.Jenis' and @id = 'Asuransi_Pembebanan_Jenis' and (text() = '
                                Simpanan
                                Pinjaman
                            ' or . = '
                                Simpanan
                                Pinjaman
                            ')]</value>
      <webElementGuid>c3529b4b-9569-44ce-904b-2f873320b4ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
