<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Rekening</name>
   <tag></tag>
   <elementGuidId>3a541e22-52a1-416b-b783-dc483494ce39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NomorRekening']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NomorRekening</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06538cd5-f20c-4706-aa9c-07b731804fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>NomorRekening</value>
      <webElementGuid>285e0bc5-55bd-4bef-9d9b-281e5c62156d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NomorRekening</value>
      <webElementGuid>c80cb69f-d07d-4e35-ba68-23e36fc20d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NomorRekening</value>
      <webElementGuid>b30930c1-7dea-4a39-9a53-802e4a1439f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-4 inputnumeric</value>
      <webElementGuid>25f55d59-3f1c-4b63-99aa-a1bee7c57d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Rekening</value>
      <webElementGuid>c0015469-ce29-479a-8c86-9cbb280e069c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2c9e5b6c-8d08-439d-9575-88da22c290c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NomorRekening&quot;)</value>
      <webElementGuid>66ea3f94-47fb-4cb6-a22a-c7fa7c8d1f1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NomorRekening']</value>
      <webElementGuid>aacc326f-335d-4546-a359-88bca5fd459b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MtInfoRekLoanForm']/div[4]/input</value>
      <webElementGuid>f4bafc82-9e87-4484-ada9-30c8fdb07f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>f9060336-e8f0-46f4-8756-07f63478be93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NomorRekening' and @id = 'NomorRekening' and @placeholder = 'Nomor Rekening']</value>
      <webElementGuid>1feba288-5bd2-47f5-b9c8-85ac1c32b6fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
