<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Flag KMK_Menjadi</name>
   <tag></tag>
   <elementGuidId>781900b2-f68c-4409-8d66-5187b72cf8e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DataInit_FlagKmk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DataInit_FlagKmk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40c02002-bd7a-4942-b660-f08626e4a48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control disabled</value>
      <webElementGuid>2c5bcc3e-56c0-49d8-af18-1af5cb7f30d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>be5ce472-775b-42f3-80ce-1b732ddb704a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The FlagKmk field is required.</value>
      <webElementGuid>0f71c004-c4ad-4c4e-9b46-1984a63c741b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>334c78c1-b5a6-4a54-b372-f99aa80aea82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DataInit_FlagKmk</value>
      <webElementGuid>1ad243d5-b8f2-4ec4-87a2-b695beee79a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DataInit.FlagKmk</value>
      <webElementGuid>050221b9-4562-455e-bbcd-f6f99a648791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d84e5dbb-6c23-428c-8087-83019b35646d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>557ce6ac-8a99-4579-a380-b926bc21229e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataInit_FlagKmk&quot;)</value>
      <webElementGuid>ba6e4dc7-aa69-408a-8ec7-bdd8c1fa5930</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DataInit_FlagKmk']</value>
      <webElementGuid>246d380c-4cce-4d03-b310-af5d3635e71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MtInfoRekLoanForm']/table/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>87e61e50-de82-4371-be1b-0eb333320454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/input</value>
      <webElementGuid>7caa9dd6-9119-4188-b398-a9fc7bf82703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DataInit_FlagKmk' and @name = 'DataInit.FlagKmk' and @type = 'text']</value>
      <webElementGuid>c0023d41-278b-420a-a3d1-d4babf38ff9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
