<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor PK Akhir Menjadi</name>
   <tag></tag>
   <elementGuidId>360ed8b2-a173-49a3-ac47-184336c67f79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DataResult_NomorPkAkhir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DataResult_NomorPkAkhir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d95686b-cf45-4d2e-ae3b-de92d7257358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>012758cf-e654-49f6-8267-30613044daaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c659ceac-4a74-4bc2-8f6a-aa67909e9e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NomorPkAkhir field is required.</value>
      <webElementGuid>dfc4472a-9e64-4748-b31a-afdbeafd52e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DataResult_NomorPkAkhir</value>
      <webElementGuid>2baf637a-989b-4f52-84cc-93d50752d5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>41345eb6-fc9e-46cc-87f7-1d6784d8c26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DataResult.NomorPkAkhir</value>
      <webElementGuid>07482085-dfd2-48f3-8a41-ec4477e3dc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor PK Akhir</value>
      <webElementGuid>818bb9cb-84fd-41de-abc9-1834a62a40c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>326f58b7-addf-48ac-bb2a-d2f1e70a60fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>428bae5b-4f8c-4656-beac-404963348450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataResult_NomorPkAkhir&quot;)</value>
      <webElementGuid>b553ea03-b4f0-42a2-bc98-7f27fd4f6532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DataResult_NomorPkAkhir']</value>
      <webElementGuid>d71a266e-a0b9-4dd5-aba9-3c27b3064060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MtInfoRekLoanForm']/table/tbody/tr[5]/td[3]/input</value>
      <webElementGuid>66dada4b-d358-4eb7-81e9-4f4eb881c490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/input</value>
      <webElementGuid>4d35bf13-d3df-4f85-9ca2-ab801e89fb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DataResult_NomorPkAkhir' and @name = 'DataResult.NomorPkAkhir' and @placeholder = 'Nomor PK Akhir' and @type = 'text']</value>
      <webElementGuid>5cfea326-bd40-4760-9571-03a53fa0bf27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
