<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sektor Ekonomi_Menjadi</name>
   <tag></tag>
   <elementGuidId>03921089-2c1c-48ad-9c4d-2c0f7f65f142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DataInit_SektorEkonomi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DataInit_SektorEkonomi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58b5c973-8f56-49ca-a594-53f36b5af173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control disabled</value>
      <webElementGuid>82692a29-b438-40ee-98f2-7bdee7dc11dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>66e674a4-ecf4-470c-ae87-f370348160bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The SektorEkonomi field is required.</value>
      <webElementGuid>6d42ca5d-e5a9-4453-8aa2-bc1712d4331b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>b61b82ad-902d-4320-9422-a7802b00ce90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DataInit_SektorEkonomi</value>
      <webElementGuid>59aac136-2249-4817-8d8e-14d467c6e09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DataInit.SektorEkonomi</value>
      <webElementGuid>22b90117-b643-4176-9e59-09b49ee5c713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d65eaec-9e29-4f82-8793-2b2cd6191ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>170900: Industri Barang Dari Kertas dan Papan Kertas Lainnya</value>
      <webElementGuid>cc61a8e8-5364-4a2c-9bdd-db792b8439cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>310d8263-17c5-415d-99a8-d5975a5103d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataInit_SektorEkonomi&quot;)</value>
      <webElementGuid>ea6336bc-9d6a-4f19-8248-e5d761443df5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DataInit_SektorEkonomi']</value>
      <webElementGuid>597b1604-d726-4fc7-b56b-bfd842df71ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MtInfoRekLoanForm']/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>4191d392-8c2e-4ca6-a787-eb2b4d336e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>1386ecd1-5229-4235-a132-fb845b97ba7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DataInit_SektorEkonomi' and @name = 'DataInit.SektorEkonomi' and @type = 'text']</value>
      <webElementGuid>f9bb7546-1c26-4952-9f57-bd6f2cd30f58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
