<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal PK Awal Menjadi</name>
   <tag></tag>
   <elementGuidId>fc5406f2-7d90-4e66-ac92-15008b54270e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DataResult_TanggalPkAwal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DataResult_TanggalPkAwal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a9d30ab-9b89-4c6a-8125-e88577b7866c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>28d79fa3-814a-4f44-ada8-8d507070721d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#tanggalPkAwalDate</value>
      <webElementGuid>30a16f8d-b51e-4ab0-a362-3190b12d6a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DataResult_TanggalPkAwal</value>
      <webElementGuid>fae7eab3-23c2-463e-968e-0ec1cef12191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DataResult.TanggalPkAwal</value>
      <webElementGuid>1872940e-f6e9-436d-8569-772a4966a6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>fb16eaaa-879a-4655-9106-5d0f57ca049e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef25d028-a9c2-4742-9ca4-7c20e74d61ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e0038ebc-b713-4f03-944c-de4ce2222326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataResult_TanggalPkAwal&quot;)</value>
      <webElementGuid>cc334df9-b4ce-4b44-b151-ee3a36413e78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DataResult_TanggalPkAwal']</value>
      <webElementGuid>510e1fa3-6273-4b62-bea7-a8fd19a4fc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tanggalPkAwalDate']/input</value>
      <webElementGuid>f795e876-6579-4ee2-9649-cfe0ca54cca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/input</value>
      <webElementGuid>926cfb18-fc80-4f3b-8ce1-1ddbd38b2705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DataResult_TanggalPkAwal' and @name = 'DataResult.TanggalPkAwal' and @placeholder = 'dd/mm/yyyy' and @type = 'text']</value>
      <webElementGuid>24caa4c9-4670-40c2-bd40-66a11242ecb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
