<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal PK Akhir Menjadi</name>
   <tag></tag>
   <elementGuidId>4cec9111-37fa-45e8-b3a9-443ddcc1809c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DataResult_TanggalPkAkhir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DataResult_TanggalPkAkhir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aca4d49a-4d77-49b1-a8a1-4ffdba2bfd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>62208d0e-731a-456f-b5c9-34316d057e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#tanggalPkAkhirDate</value>
      <webElementGuid>938df70b-f8f5-4149-a954-103752b62bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DataResult_TanggalPkAkhir</value>
      <webElementGuid>f5e1c22a-57ec-43da-9175-9b7daaf945b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DataResult.TanggalPkAkhir</value>
      <webElementGuid>ba9fbab1-ba80-4634-9c93-cc4035818352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>64e20f32-aecd-41f7-acbf-d7d5f9139882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c708a2dd-97ce-4c14-b746-33c4230570f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>364501b7-0871-49d3-bd2a-91b39ec5e5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataResult_TanggalPkAkhir&quot;)</value>
      <webElementGuid>ec8fccf2-d791-4a45-847c-39386820a384</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DataResult_TanggalPkAkhir']</value>
      <webElementGuid>67e26c55-3fd1-4e38-9800-8ade999a91e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tanggalPkAkhirDate']/input</value>
      <webElementGuid>402f62c3-bb3b-4f98-81a2-5f9fbda38965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[3]/div/input</value>
      <webElementGuid>31ac8e25-5297-4f67-bbc2-f868015d37fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DataResult_TanggalPkAkhir' and @name = 'DataResult.TanggalPkAkhir' and @placeholder = 'dd/mm/yyyy' and @type = 'text']</value>
      <webElementGuid>f406806f-a62e-454d-a32f-c0e8d3a364c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
