<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor PK Awal Menjadi</name>
   <tag></tag>
   <elementGuidId>4b4490fe-0e64-4c67-9a48-6c55e93eee06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DataResult_NomorPkAwal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DataResult_NomorPkAwal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a960e83-1264-4e50-a6cc-52f0da2e7b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>412ee3cf-9bef-4586-932b-0502f0a7a2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b4dc9625-6390-4c20-a9b7-3bacbadc3e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NomorPkAwal field is required.</value>
      <webElementGuid>938db333-9a71-48ff-bea4-c3cc4403af99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DataResult_NomorPkAwal</value>
      <webElementGuid>17ddf320-7443-49c4-94e1-73b510b6faf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>101a1d7f-538d-4370-bfb4-33526b888598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DataResult.NomorPkAwal</value>
      <webElementGuid>52986275-548b-433e-980a-cc4088da2ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor PK Awal</value>
      <webElementGuid>3978878e-ffe9-48df-a7f2-0486e8d04a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a97a39fb-3bf6-4dbd-9307-cc604a3d1c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2195e2af-82fa-4304-8495-f1d2a0d57189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataResult_NomorPkAwal&quot;)</value>
      <webElementGuid>fbdaecd5-6add-458e-9650-5a614fbc6e04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DataResult_NomorPkAwal']</value>
      <webElementGuid>e9f47dda-70c1-4bbd-a400-afca07305a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MtInfoRekLoanForm']/table/tbody/tr[4]/td[3]/input</value>
      <webElementGuid>d5442258-e0d4-4589-8087-dd32cf5d0d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>c832195f-ec43-46b7-8919-73657bf6fa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DataResult_NomorPkAwal' and @name = 'DataResult.NomorPkAwal' and @placeholder = 'Nomor PK Awal' and @type = 'text']</value>
      <webElementGuid>ca397e35-ff89-441e-ac70-4e777745393f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
