<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Peruntukan_Menjadi</name>
   <tag></tag>
   <elementGuidId>eaae982a-ec99-4da7-b458-de75d546739b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DataInit_KodePeruntukan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DataInit_KodePeruntukan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52fafdaf-d396-4bce-a71c-63f11f044752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control disabled</value>
      <webElementGuid>695a9796-c9f8-45a1-a0fc-1a4e9acfa602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d499831e-ce75-4dd3-8674-d3a82d290652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The KodePeruntukan field is required.</value>
      <webElementGuid>4c150d77-f5fd-4bc5-a357-a069e17c486e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>da6221bd-063f-4fb8-bee4-86c559709aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DataInit_KodePeruntukan</value>
      <webElementGuid>9a37ae26-102d-4565-89b3-12265de030f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DataInit.KodePeruntukan</value>
      <webElementGuid>7ecb07fc-d233-4434-8214-e0d42f8dc05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d80a505-670a-4c3a-9451-b5fe56d3bd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>105</value>
      <webElementGuid>bcdd1988-b0e9-4789-9224-775d2be0eee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>26fbdcb3-e064-4d58-80a4-fa9bab88e2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataInit_KodePeruntukan&quot;)</value>
      <webElementGuid>e47e1bfe-e70f-4247-a143-47aa5a65d0ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DataInit_KodePeruntukan']</value>
      <webElementGuid>5e9e8ba5-6989-42c4-ba5a-b0413e3245cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MtInfoRekLoanForm']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>50fdc226-96c8-4530-830f-7c8c15d76107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>b629b5de-c3de-48e4-863b-bc7cfece5ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DataInit_KodePeruntukan' and @name = 'DataInit.KodePeruntukan' and @type = 'text']</value>
      <webElementGuid>ac7ea4ab-c008-401c-b224-9875c1c4cc97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
