<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select2_SektorEkonomi</name>
   <tag></tag>
   <elementGuidId>09d43fba-d9b7-4c35-9964-ea8d33564965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-DataResult_SektorEkonomi-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-DataResult_SektorEkonomi-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>55153caa-657b-4a16-9c3d-93f36eda0baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>01c55a15-ab5e-464c-823d-52da1ed66c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-DataResult_SektorEkonomi-container</value>
      <webElementGuid>909bf692-b1d3-4273-8d31-22b28dd06718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1e31caf7-5da1-4664-9162-25a8c9db8ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>90ed50e8-60fa-4f59-ac89-337adfd8ac44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>0063b42c-c2fd-482c-9104-d3e5ff11cca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>18f728fc-bf8e-4902-88f9-65cf736dcfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-DataResult_SektorEkonomi-container&quot;)</value>
      <webElementGuid>a1647eb4-4095-48cd-90c9-29a7672fefd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-DataResult_SektorEkonomi-container']</value>
      <webElementGuid>22b489f4-5ce2-450d-948f-cd6acfc0f7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MtInfoRekLoanForm']/table/tbody/tr[3]/td[3]/span/span/span/span</value>
      <webElementGuid>65beab89-eb14-4599-9161-780de1a341eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/span/span/span/span</value>
      <webElementGuid>07b44bfb-e07c-420c-afdb-9312ce425de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-DataResult_SektorEkonomi-container' and @title = '-' and (text() = '-' or . = '-')]</value>
      <webElementGuid>c78f6651-8d35-4b20-bc7c-80f28ba9afb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
