<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select2_KodePeruntukan</name>
   <tag></tag>
   <elementGuidId>d643fc0b-df65-46e0-9f8d-9e5aca61106c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-DataResult_KodePeruntukan-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-DataResult_KodePeruntukan-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7cc2a07-acf4-448e-92bb-6affb15b8233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>69ed1532-0ee4-4bb4-92bb-a2e7dd2ac41f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-DataResult_KodePeruntukan-container</value>
      <webElementGuid>715a0ec4-209c-43b3-a341-98a4e99f76ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>64ac6ebc-ab11-409a-b59d-3ebcd1c0e8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>03c667d4-4b26-451b-bb55-be659dc18ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>6ba13a78-1977-4770-8e89-339568b06724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>6482dc8b-5221-43e3-ab03-96af18fc4517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-DataResult_KodePeruntukan-container&quot;)</value>
      <webElementGuid>f191a004-cd11-4f76-b8ed-163feb55cd23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-DataResult_KodePeruntukan-container']</value>
      <webElementGuid>c256fe0a-fd2d-4fe6-8a20-202983b71e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MtInfoRekLoanForm']/table/tbody/tr[2]/td[3]/span/span/span/span</value>
      <webElementGuid>47c51e97-c507-437e-a3e4-c68748311303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>206d5f2b-90ad-4e51-806d-dffa8422f5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-DataResult_KodePeruntukan-container' and @title = '-' and (text() = '-' or . = '-')]</value>
      <webElementGuid>e3a8605b-abf6-44ad-9d5e-d7424c103969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
