<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoRek</name>
   <tag></tag>
   <elementGuidId>b31fb7d2-5199-4d50-bff3-059746a03a9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NomorRekening']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NomorRekening</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7daa00a-3c0f-4366-918e-815223bb4b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>NomorRekening</value>
      <webElementGuid>80a48752-e757-4244-b529-a127a1ba7657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NomorRekening</value>
      <webElementGuid>028d708a-2d49-4a02-81f1-c9d7a1f2b769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NomorRekening</value>
      <webElementGuid>92faf36d-9e0e-49e4-84cc-252e048a8ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inputnumeric</value>
      <webElementGuid>9e2057bf-2ad8-4580-b93c-0e70e8ea258f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Rekening</value>
      <webElementGuid>ee0f1b60-e3e1-41e0-b9fa-1ac8f34f5b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b86d68f6-9b1c-4e86-8faa-4465c9f6ce15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NomorRekening&quot;)</value>
      <webElementGuid>2c269e5a-9e15-4e1d-a3e7-9cecfea380e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NomorRekening']</value>
      <webElementGuid>8b55fc5b-6edb-436d-9fc2-7f24a66cfe12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='RestrukturisasiRekeningForm']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>ef40a6f8-7e6b-4e25-9f7e-ffae5c2b0335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>d75a9fa7-5c83-4d3b-9ad6-88d5575e4a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NomorRekening' and @id = 'NomorRekening' and @placeholder = 'Nomor Rekening']</value>
      <webElementGuid>acbd5fbb-5150-45a2-a988-ca05570993c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
