<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TglRestruk</name>
   <tag></tag>
   <elementGuidId>15235075-c589-4377-82ca-3b1cf0faa0ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TglRestruk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TglRestruk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0df217b1-7d02-435f-8e79-8e380a0f4c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>4ddfa7de-46a7-4898-8a14-084ed9ba75c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TglRestruk</value>
      <webElementGuid>543158e0-32cd-41cd-9d4c-91812bdc62cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TglRestruk</value>
      <webElementGuid>5fbfb4d2-14c0-4e93-8102-35408457fb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tgl Restruk</value>
      <webElementGuid>4394433a-656b-45e2-8596-9dac416ac15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94c9b010-0cea-4e09-b765-43bfcdbd0ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>628ce71d-c201-4eef-a884-55b2f4cafe31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TglRestruk&quot;)</value>
      <webElementGuid>d70127d3-16c6-4b65-b08d-901d67fefaa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TglRestruk']</value>
      <webElementGuid>9cc49fa3-94a7-464c-9edc-2e4b99731805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='RestrukturisasiRekeningForm']/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>dc1fdc48-8230-4a3a-ad74-330bb5396901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>9907781d-884f-4f22-b2a5-fa6332e6ec79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TglRestruk' and @name = 'TglRestruk' and @placeholder = 'Tgl Restruk' and @type = 'text']</value>
      <webElementGuid>14b143c0-42dd-4f55-b4d6-f0cd6b4d9f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
