<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Frekuensi</name>
   <tag></tag>
   <elementGuidId>5b981851-ff57-4a3b-b768-22bd848878cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Frekuensi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Frekuensi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b352ed28-cae7-463d-8b79-044457bcf0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0be4bb0c-101c-4c0f-b778-430e9b10972a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Frekuensi</value>
      <webElementGuid>eeba10ed-5424-4500-8396-75fa68b13190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>575d57ce-02a9-418e-8176-8b4088847f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Frekuensi</value>
      <webElementGuid>c6eaf014-d27d-4b9f-9705-dbbe700c82d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Frekuensi</value>
      <webElementGuid>12593936-2fb6-4758-ac19-5c6894e87670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2da7e77f-66b8-4d1a-9f9e-0addacd0fc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b3d6285a-8d33-4ba8-bab1-e567503380a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Frekuensi&quot;)</value>
      <webElementGuid>0e5c1415-8007-4594-bf11-cc69fbbb9de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Frekuensi']</value>
      <webElementGuid>ad80e159-4cb3-4c3f-80ec-7b691f115d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='RestrukturisasiRekeningForm']/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>6222d04e-2d40-447f-acb5-9b3e1cc61a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>91b6adeb-66e7-4949-97a2-3c8f34977b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Frekuensi' and @name = 'Frekuensi' and @placeholder = 'Frekuensi' and @type = 'text']</value>
      <webElementGuid>1cdeb32a-4633-4b5f-82c6-64fdbee1efb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
