<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Metode Restrukturisasi</name>
   <tag></tag>
   <elementGuidId>b12c1a9c-3a00-41cc-be4f-a7583fe73c2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DataResultMetodeRestruk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DataResultMetodeRestruk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c2b32508-e7cc-41c0-a167-2cbcc9e4c275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DataResultMetodeRestruk</value>
      <webElementGuid>1ab8a43a-583a-4695-bb04-1238e6786187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c774d539-a412-47f7-9bdd-e9c2f99bfcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1: Penurunan suku bunga kredit2: Perpanjangan jangka waktu kredit3: Pengurangan tunggakan pokok kredit4: Pengurangan tunggakan bunga kredit5: Penambahan fasilitas kredit6: Konversi kredit menjadi Penyertaan Modal Sementara7: Penambahan fasilitas kredit dan pengurangan tunggakan bunga kredit8: Penambahan fasilitas kredit dan perpanjangan jk waktu kredit9: Penambahan fasilitas kredit dan penurunan suku bunga0: Penambahan fasilitas kredit, pengurangan tunggakan bunga kredit dan penurunan suku bunga kreditA: Penambahan fasilitas kredit,  pengurangan tunggakan bunga kredit, dan perpanjangan jangka waktu kreditB: Lainnya</value>
      <webElementGuid>4479d9fb-629c-486e-b413-7c71c354d3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataResultMetodeRestruk&quot;)</value>
      <webElementGuid>15791aa3-b576-4fd4-ab8d-29c226292f9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DataResultMetodeRestruk']</value>
      <webElementGuid>cc32f580-2285-4c98-babe-5aa503071685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='RestrukturisasiRekeningForm']/table[2]/tbody/tr[3]/td[3]/select</value>
      <webElementGuid>e29c29d8-ed5a-49d4-b11f-71678112460d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/select</value>
      <webElementGuid>7b8afaac-da73-4292-bf48-2ca00a6f79fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DataResultMetodeRestruk' and (text() = '1: Penurunan suku bunga kredit2: Perpanjangan jangka waktu kredit3: Pengurangan tunggakan pokok kredit4: Pengurangan tunggakan bunga kredit5: Penambahan fasilitas kredit6: Konversi kredit menjadi Penyertaan Modal Sementara7: Penambahan fasilitas kredit dan pengurangan tunggakan bunga kredit8: Penambahan fasilitas kredit dan perpanjangan jk waktu kredit9: Penambahan fasilitas kredit dan penurunan suku bunga0: Penambahan fasilitas kredit, pengurangan tunggakan bunga kredit dan penurunan suku bunga kreditA: Penambahan fasilitas kredit,  pengurangan tunggakan bunga kredit, dan perpanjangan jangka waktu kreditB: Lainnya' or . = '1: Penurunan suku bunga kredit2: Perpanjangan jangka waktu kredit3: Pengurangan tunggakan pokok kredit4: Pengurangan tunggakan bunga kredit5: Penambahan fasilitas kredit6: Konversi kredit menjadi Penyertaan Modal Sementara7: Penambahan fasilitas kredit dan pengurangan tunggakan bunga kredit8: Penambahan fasilitas kredit dan perpanjangan jk waktu kredit9: Penambahan fasilitas kredit dan penurunan suku bunga0: Penambahan fasilitas kredit, pengurangan tunggakan bunga kredit dan penurunan suku bunga kreditA: Penambahan fasilitas kredit,  pengurangan tunggakan bunga kredit, dan perpanjangan jangka waktu kreditB: Lainnya')]</value>
      <webElementGuid>f8eae467-c6b1-409c-8bf5-62064f0f0aa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
