<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Deskripsi</name>
   <tag></tag>
   <elementGuidId>1ab90648-3844-4313-a972-27a17529c357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Deskripsi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Deskripsi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>62edb096-e66d-49e1-9caa-b549832f3b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3987a407-00c3-49c0-84c5-8cd4ce410bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Deskripsi</value>
      <webElementGuid>1dd82022-dc2d-4528-9555-b3141eeb4bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b795a35e-afa2-4908-a934-69f22ba71d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Deskripsi</value>
      <webElementGuid>62b51cd4-c663-4d6f-9f8b-c641b71457a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Deskripsi</value>
      <webElementGuid>25ee882d-1e1e-4554-949e-d5ffc13a43fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>b53bc482-2f6f-4c83-bc1c-2f5089364f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Deskripsi&quot;)</value>
      <webElementGuid>37bd37c5-e41e-4590-bfd6-1842262a78a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Deskripsi']</value>
      <webElementGuid>e8c8da1c-ac6b-449e-9179-27f17eb7c271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='RestrukturisasiRekeningForm']/table/tbody/tr[8]/td[2]/textarea</value>
      <webElementGuid>bbaafc80-ed06-4902-840f-7f6ecc93df1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ff58bbc3-9cbf-44df-8a3e-e5a30006aec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Deskripsi' and @name = 'Deskripsi' and @placeholder = 'Deskripsi']</value>
      <webElementGuid>c346cfdb-7068-4f01-8f01-6c967ccc6e49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
