<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_choose-agent_coc or escrow</name>
   <tag></tag>
   <elementGuidId>5b6ba344-7c32-4497-8b32-1c5bcc7c7ae1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='choose-agent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#choose-agent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7ef41d13-18d8-446c-93c2-f090267acc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>4da8eb02-29ee-444d-8dda-d6db393ca212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Switch Alur Proses Pembukuan</value>
      <webElementGuid>971aad65-6a4c-4dd4-bea7-de46fdad086c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choose-agent</value>
      <webElementGuid>565f5056-228c-44a5-9ce1-ad2c22ea96f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choose-agent&quot;)</value>
      <webElementGuid>32aaffa5-e11b-4c40-892b-90c61927d4f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='choose-agent']</value>
      <webElementGuid>490003e2-c5c1-4851-beb8-095a724b08aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-adc']/div/div/button</value>
      <webElementGuid>d05c3528-aabd-4cc0-83d1-9ee0545cc698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>20bff1cb-4a8a-4028-bb54-e6946aaedf8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Switch Alur Proses Pembukuan' and @id = 'choose-agent']</value>
      <webElementGuid>5b09ddcf-a465-438a-bd6e-ea35027e8bff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
