<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_inquiry</name>
   <tag></tag>
   <elementGuidId>a44d4ec9-aa78-4e42-b21f-9fc8677e0c10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@title = 'Inquiry']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Inquiry']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-outline-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82164153-276a-4abd-9907-59ae990cc9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-secondary</value>
      <webElementGuid>c3b4118d-b6f5-4bda-8a3d-423d3be8f071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name&quot;</name>
      <type>Main</type>
      <value>buttonInquiry&quot;</value>
      <webElementGuid>ae993cd8-2ff2-4ad3-9f69-46942ae157a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>NEW</value>
      <webElementGuid>595f3444-8e24-4a37-b66c-e7e1435b7452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>01f89ddc-0c83-4093-a5bc-e635627c564f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>e4a3053a-b25e-4ebe-b4bd-abfb1e8fe7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Inquiry</value>
      <webElementGuid>08cfee64-c320-4b3c-9da5-002b9647c4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;activityTable&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[7]/button[@class=&quot;btn btn-outline-secondary&quot;]</value>
      <webElementGuid>81ff2de0-94dd-4789-95d3-2c6b7e810bb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='activityTable']/tbody/tr/td[7]/button[2]</value>
      <webElementGuid>3c0b8f61-2754-447e-a627-70b9a9c04943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>46538c4e-4ca3-4fa1-9d95-b30fce611f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Inquiry']</value>
      <webElementGuid>c0fb7eb4-49d3-4dc4-9403-46cc49a37c76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
