<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Inquiry All</name>
   <tag></tag>
   <elementGuidId>cec729a6-78ea-4aaf-b653-78e64025cda1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-database</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[(text() = ' Inquiry All ' or . = ' Inquiry All ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2f7e9da9-8195-4349-a73b-aeaf6554c6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-database</value>
      <webElementGuid>faabfd28-c726-4a69-ac1e-102fcfa70c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>InquiryAll(40472)</value>
      <webElementGuid>dee066f5-df7a-447b-8493-57c1723dad25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Inquiry All </value>
      <webElementGuid>7ac648f8-f5cb-4a46-a358-282e2567fa72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-adc&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;btn-group&quot;]/a[@class=&quot;btn btn-default text-primary&quot;]/i[@class=&quot;fas fa-database&quot;]</value>
      <webElementGuid>8c323f9a-602b-4cbe-a9ba-b0450385fa86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@onclick='InquiryAll(40472)']</value>
      <webElementGuid>d22190bf-3c54-447a-849e-c6745b4e6d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-adc']/div[2]/div[9]/div/a[2]/i</value>
      <webElementGuid>492eb96c-3a38-4252-8682-8c1f8c0b3213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::i[1]</value>
      <webElementGuid>11d231c7-bcd4-4fe3-b2ca-9561b8cc5e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Activity'])[1]/following::i[2]</value>
      <webElementGuid>33b34082-6517-44cb-9a07-856668685184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/preceding::i[1]</value>
      <webElementGuid>ecc57f5d-f7fa-4fd6-9579-f91269a17695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::i[2]</value>
      <webElementGuid>a787cc33-5e72-4276-b2f7-ba8afe0f0d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inquiry All']/parent::*</value>
      <webElementGuid>d63f0493-89d6-4de0-bd8d-85b30e3b45ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>93bf95fa-d91f-471b-970f-260630ca797a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = ' Inquiry All ' or . = ' Inquiry All ')]</value>
      <webElementGuid>aa6bcda6-6438-49ae-8860-d9fdc119d8a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
