<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoTestKey</name>
   <tag></tag>
   <elementGuidId>82da4ef0-92f3-4ce8-a4b1-075f58be0cbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NoTestKey']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NoTestKey</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddd70195-9ba3-4fd0-bbbf-8557cb32658f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>NoTestKey</value>
      <webElementGuid>c4283f0b-c8bb-4996-92d9-133e1040fe07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NoTestKey</value>
      <webElementGuid>5aff8530-0522-4c05-b641-4a5d970eb766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NoTestKey</value>
      <webElementGuid>d1ccd1a9-860f-4017-bac0-0f960046ce93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-4</value>
      <webElementGuid>51f1b949-8701-46dc-9b64-c2b3386be916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Memo</value>
      <webElementGuid>dd1c1a46-b83f-4838-9297-b835a6a8aeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>90689621-d07a-4b46-addd-f2adb850c8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NoTestKey&quot;)</value>
      <webElementGuid>79b6ba56-5ded-469a-907d-8217eebeb2e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NoTestKey']</value>
      <webElementGuid>f114be87-c7b2-431e-94e2-20367c1dc826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-adc']/div[2]/div[2]/input[2]</value>
      <webElementGuid>bc9383d2-5fea-4d84-b3c1-a271ee7702ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>75618388-c07c-4186-a282-339a8c8efb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NoTestKey' and @id = 'NoTestKey' and @placeholder = 'Nomor Memo']</value>
      <webElementGuid>138505df-6a11-44cc-b7b4-e385447311da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
