<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_choose-agent_coc or escrow</name>
   <tag></tag>
   <elementGuidId>450a1afe-ca06-4ccc-baa4-d348f9f9970e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='choose-agent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#choose-agent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66adfcec-638f-41ee-9446-7c363618bcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>5074c1b2-5436-41cc-af13-deab24d06d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Switch Alur Proses Pembukuan</value>
      <webElementGuid>b992c093-7ab6-4724-a680-b51f5c8d569f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choose-agent</value>
      <webElementGuid>c933bb11-1ed7-4ee0-9042-a10469aef40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choose-agent&quot;)</value>
      <webElementGuid>4511f5a7-5e3b-4294-8edc-b4a9bdd950c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='choose-agent']</value>
      <webElementGuid>aedef2d9-0f50-48f0-bae0-9f73804f9d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-adc']/div/div/button</value>
      <webElementGuid>0cd717c8-0afb-46a5-a990-33c396bef7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4a161983-e445-4ff6-9fca-8e26298cf32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Switch Alur Proses Pembukuan' and @id = 'choose-agent']</value>
      <webElementGuid>e120b59d-88b8-4c07-8f77-b32a49678a50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
