<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NomorRekening</name>
   <tag></tag>
   <elementGuidId>85179ddc-ffe1-4dd6-911f-06b7b492f868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NomorRekening']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NomorRekening</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2918b375-9eee-4248-b309-e692cdacd65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>NomorRekening</value>
      <webElementGuid>abd03571-7832-47b1-9313-c610ea00ceb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NomorRekening</value>
      <webElementGuid>25e42205-3c43-4fff-99ed-00f7e43ce2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NomorRekening</value>
      <webElementGuid>8934dff9-0240-444c-b147-6b4082601706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-6 inputnumeric</value>
      <webElementGuid>1c450af8-78d0-427b-b2ec-be889dc5a5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Rekening</value>
      <webElementGuid>69f63567-8bfe-4c72-af07-9794b6d0f5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>48d2007d-3faf-4134-b684-dad91443dce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NomorRekening&quot;)</value>
      <webElementGuid>79f7fdef-4c96-4c79-8f62-dd0f0ce67fdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NomorRekening']</value>
      <webElementGuid>7f32c240-4d2c-402c-833d-0c60393b5eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='BlokirRekeningForm']/div[3]/input</value>
      <webElementGuid>3299b5ea-be69-487f-8cf3-6d814e042238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>a8c925b9-b5e2-41af-9e9a-bef75f46351f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NomorRekening' and @id = 'NomorRekening' and @placeholder = 'Nomor Rekening']</value>
      <webElementGuid>56c5cb6b-80c9-4200-af2d-c2775af261dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
