<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NominalBlokir</name>
   <tag></tag>
   <elementGuidId>38acb6a4-139b-4eca-94a4-2c29014928b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NominalBlokir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NominalBlokir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c1571cb-8d3a-4c37-a2ad-e79e41425d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-6</value>
      <webElementGuid>403c6ae8-ef47-445f-9f4a-52bd79ef9fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9df72e45-9692-4773-a919-2bf7ea946dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field NominalBlokir must be a number.</value>
      <webElementGuid>37c7e1ae-f010-43fc-a0ba-f7d9c8c66bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NominalBlokir field is required.</value>
      <webElementGuid>f991b8a3-35e3-4b1d-a8fb-fac4049ce43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NominalBlokir</value>
      <webElementGuid>dabaa00a-c2da-4d74-b57a-642b97ec6a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NominalBlokir</value>
      <webElementGuid>e714fc8b-ec7b-45ba-bb00-53ec1468ef44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nominal Blokir</value>
      <webElementGuid>3ba7d482-e1e9-415b-8791-afaa2ad04798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96cb3403-2ec8-4b7c-80d4-b4e4707eb0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0,00</value>
      <webElementGuid>c0ef922d-6566-42e5-9d05-da89eab5c499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f41efafb-892a-4f61-8fca-c93031e3db1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NominalBlokir&quot;)</value>
      <webElementGuid>f479e866-fc54-41c7-b410-678bdb6607f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NominalBlokir']</value>
      <webElementGuid>c89498a8-6f51-4784-93a6-f099c30de591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='BlokirRekeningForm']/div[11]/input</value>
      <webElementGuid>175693cb-103d-4d01-8694-c2b0c4174f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>8d210b92-c5f6-4926-8d31-a400f3ff14fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NominalBlokir' and @name = 'NominalBlokir' and @placeholder = 'Nominal Blokir' and @type = 'text']</value>
      <webElementGuid>aa731b77-f4ff-448d-9af4-fa21c6e5d38a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
