<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NarasiBlokir2</name>
   <tag></tag>
   <elementGuidId>b6e9703d-f252-49f4-9b72-a8fdd35d076b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NarasiTambahan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NarasiTambahan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64c131fd-5bfa-4c1b-bfe7-996b48c18688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>NarasiTambahan</value>
      <webElementGuid>a0d464a0-9b17-467a-b200-36ccb99cd58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NarasiTambahan</value>
      <webElementGuid>af4fcfaf-fc92-42a6-97ba-490910ffc98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NarasiTambahan</value>
      <webElementGuid>b501d402-33ac-43e8-bb23-5dc12bd544a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-6</value>
      <webElementGuid>7604d170-c7ae-4631-850f-7fd56bb36408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Narasi Blokir 2</value>
      <webElementGuid>09ca8798-9fa9-4918-83dc-d94e0935f169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e2027696-a65e-4732-99ed-c493ae25c28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fbda905a-d773-4e02-a94b-cd06d653630a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NarasiTambahan&quot;)</value>
      <webElementGuid>1bf42e60-2ec4-42ef-8bde-e95c4a533633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NarasiTambahan']</value>
      <webElementGuid>ce05c036-8dec-4ae7-baff-f01486e83d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='BlokirRekeningForm']/div[13]/input</value>
      <webElementGuid>0822c2b3-a480-49bc-a4ba-ed64edfa9931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/input</value>
      <webElementGuid>73b25fbd-8682-406b-b130-78bec375405f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NarasiTambahan' and @id = 'NarasiTambahan' and @placeholder = 'Narasi Blokir 2']</value>
      <webElementGuid>b42c4769-58f5-4c53-8678-4de1df2b7042</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
