<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NarasiBlokir1</name>
   <tag></tag>
   <elementGuidId>321ff9bf-b829-453e-88f1-ea31e623cf47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NarasiBlokir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NarasiBlokir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6691fad-18e9-458b-aa70-71ea46cdf2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>NarasiBlokir</value>
      <webElementGuid>bcb4f6b6-a211-4d66-befc-be423e6105c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Pesan</value>
      <webElementGuid>db8d2acc-af3c-49ca-97cb-72e8f8e91bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NarasiBlokir</value>
      <webElementGuid>44f3db1c-f197-4e65-877d-5458047bad23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-6</value>
      <webElementGuid>90f63ab3-9183-4d1a-aac7-f98081b5e682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Narasi Blokir</value>
      <webElementGuid>e753c975-171f-4ea9-a8d3-673f70b64d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>48688169-c74b-4483-ac58-4258b34b1af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d7863c55-edae-4357-bc37-8e59f86365c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NarasiBlokir&quot;)</value>
      <webElementGuid>b2c68e55-50da-447b-b230-46d0a7fb3ca0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NarasiBlokir']</value>
      <webElementGuid>3f5871c8-a11e-449f-9881-f9f06ca5cff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='BlokirRekeningForm']/div[12]/input</value>
      <webElementGuid>406c2bd9-17f6-4876-a856-c3967e2083f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>e5705a82-4209-4c50-921c-46e6338146f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Pesan' and @id = 'NarasiBlokir' and @placeholder = 'Narasi Blokir']</value>
      <webElementGuid>5642a823-1ff3-4e65-9a85-85793218ef80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
