<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PasangOrLepas</name>
   <tag></tag>
   <elementGuidId>92ef42b3-8bac-4ee5-bc8b-ec1b982e3b51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='listPerlakuanBlokir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#listPerlakuanBlokir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ef8b2563-bd9e-40af-8743-82d87470d210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-control col-md-6</value>
      <webElementGuid>94b65f51-3265-453b-8a98-858da3f86e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>PerlakuanBlokir</value>
      <webElementGuid>08ed84ea-7377-463c-a33e-62002d255617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>perlakuanChanged(true, '')</value>
      <webElementGuid>48db6631-d8da-4ce2-8582-02447ffd1148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PerlakuanBlokir</value>
      <webElementGuid>e291babd-1d06-44c2-90f7-3abc3bfa7bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>listPerlakuanBlokir</value>
      <webElementGuid>706bb23d-8ecf-4865-ab60-fa1d4961eea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            --- Pilih Opsi ---
                            Pasang
                            Lepas
                        </value>
      <webElementGuid>d8dc5b67-94c4-48d5-ace8-830ec25d2b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listPerlakuanBlokir&quot;)</value>
      <webElementGuid>7c2e8ffa-e29e-4c96-ba41-71ce27622cea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='listPerlakuanBlokir']</value>
      <webElementGuid>2f575c99-be1f-44b9-8550-cce07f044bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='BlokirRekeningForm']/div[6]/select</value>
      <webElementGuid>ba2b7cfb-df04-4695-a245-4b157a934839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4754036e-8cac-4c97-b1d8-810e9f591d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'PerlakuanBlokir' and @id = 'listPerlakuanBlokir' and (text() = '
                            --- Pilih Opsi ---
                            Pasang
                            Lepas
                        ' or . = '
                            --- Pilih Opsi ---
                            Pasang
                            Lepas
                        ')]</value>
      <webElementGuid>afc7bb7e-de39-4778-a0e0-97295de18c12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
