<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update - backup</name>
   <tag></tag>
   <elementGuidId>5d0f52f2-313d-48d7-a8d1-0820095a2787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4511ac43-8991-45dc-91ef-18d353d102d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonSubmit</value>
      <webElementGuid>ac96e0a3-7f4c-40f5-afee-9eca6272d131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>bb8d9258-346f-4c04-88de-1648339f3049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>checkAlertSaldo('False', 'Inquiry Incomplete')</value>
      <webElementGuid>2c193110-4ff3-4988-94ad-a1defa16a48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>80910d09-9638-4ffd-8016-cdc60392fd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonSubmit&quot;)</value>
      <webElementGuid>b312c837-52db-4e00-ae26-076b825031e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonSubmit']</value>
      <webElementGuid>479a9df3-c342-4cd6-9d77-8e1a7918d033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>147a8199-6cff-49b5-99f7-a6f9bfbf32a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonSubmit' and (text() = 'Update' or . = 'Update')]</value>
      <webElementGuid>d281ca9f-220c-458d-93be-8fce1cee0f75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
