<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_filter_no_batch</name>
   <tag></tag>
   <elementGuidId>d86fdd84-15e8-4a68-ae31-0ef5eb590968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22b5db1d-6411-4069-b3a4-ea401de03762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5327eef2-b33e-4f74-92b7-3308a76c2fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>505fe7dd-be40-42ee-969d-139decc5bfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adminKreditBatchTable&quot;)/div[@class=&quot;jsgrid-grid-header jsgrid-header-scrollbar&quot;]/table[@class=&quot;jsgrid-table table table-bordered&quot;]/tr[@class=&quot;jsgrid-filter-row&quot;]/td[@class=&quot;jsgrid-cell&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>bec6f285-5858-4732-bc04-58ab7287f700</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>f30003e3-564c-4ffb-a2e7-3076aefe6171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adminKreditBatchTable']/div/table/tr[2]/td[3]/input</value>
      <webElementGuid>e181f192-1f17-45ad-a173-c5ffb736db38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>4ba3a900-a559-46a9-b7bd-747826a5812d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>5089dc37-127a-426a-9607-0c8718a854ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
