<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_approver</name>
   <tag></tag>
   <elementGuidId>133aea53-0402-49e5-a49e-574ecb621e4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-NextApprover-result-0x6t-30028']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-NextApprover-result-0x6t-30028</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a3c79ae0-d1dd-42c0-960e-b14d2a945a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>6999968e-38b5-4af5-9436-85fbd9fd44ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-NextApprover-result-0x6t-30028</value>
      <webElementGuid>3d0487db-dd92-4cbd-a5c2-558b957ce13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9f7c1c5b-c22f-4ea2-8402-11ca16576a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7e7d08c3-04ea-459f-a846-71a964677e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-NextApprover-result-0x6t-30028</value>
      <webElementGuid>8f5772de-3742-4573-9e0a-bcd6ec00bde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>M. FAHREZI WIJAYA RETAIL CREDIT OPERATIONS TEAM LEADER 1</value>
      <webElementGuid>be0db259-c9ca-4b80-b6b9-f4f991952255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-NextApprover-result-0x6t-30028&quot;)</value>
      <webElementGuid>0bc21802-3a83-4be3-a2cc-f9698b777797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-NextApprover-result-0x6t-30028']</value>
      <webElementGuid>a0e6da9f-bea2-4113-a7bb-c638fd3dda0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-NextApprover-results']/li[3]</value>
      <webElementGuid>eaba00ad-f544-466a-960e-a6d78a28730b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>5a77855c-6d94-411c-87d8-61894e6b4d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-NextApprover-result-0x6t-30028']</value>
      <webElementGuid>b4828611-3385-4fce-a436-1d4ba7d7c904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
