<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_button</name>
   <tag></tag>
   <elementGuidId>7910f4e2-a6bc-4604-81ee-220b4f929595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.jsgrid-button.jsgrid-search-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65e2b8ea-2d5e-495b-a224-1b34dae0f143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsgrid-button jsgrid-search-button</value>
      <webElementGuid>c59d6585-a665-42cf-ac7c-9b8aad49419a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc673115-2a80-4b91-9172-a691c1ae0f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>bbf71398-7f17-4fa0-a2ea-b419cb3fff1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adminKreditBatchTable&quot;)/div[@class=&quot;jsgrid-grid-header jsgrid-header-scrollbar&quot;]/table[@class=&quot;jsgrid-table table table-bordered&quot;]/tr[@class=&quot;jsgrid-filter-row&quot;]/td[@class=&quot;jsgrid-cell jsgrid-control-field jsgrid-align-center&quot;]/input[@class=&quot;jsgrid-button jsgrid-search-button&quot;]</value>
      <webElementGuid>6f677a53-961f-4aee-8353-8c4edc4c252b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='button'])[2]</value>
      <webElementGuid>111d9a3f-68e9-4546-bb0d-5d7e0248d50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adminKreditBatchTable']/div/table/tr[2]/td[8]/input</value>
      <webElementGuid>20e1cb0a-8969-4862-a09c-2f73ac9cc105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>a0e8d8aa-d4bf-4c87-98a8-e8826db290be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @title = 'Search']</value>
      <webElementGuid>11bfe39d-203b-44dd-a21e-ab9bc6e5da9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
