<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih RM</name>
   <tag></tag>
   <elementGuidId>12e88cf8-3c0c-48db-9aec-363049d26186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-rm-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-rm-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fbc89f52-1b42-4636-be06-8ca79ea5cba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>c697fcfa-d2a2-4818-b1b0-345d9dcadbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-rm-container</value>
      <webElementGuid>f96d6be5-ae61-416e-9dd0-cecb7f626047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a71ec8da-1b70-434f-855e-e8c8b76fa328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>49da7d16-5d16-4eba-b78e-16a85c8ce56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>--Pilih RM--</value>
      <webElementGuid>bea9914b-76f0-47e0-96eb-9ff565c44123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Pilih RM--</value>
      <webElementGuid>112ecbed-2a9d-4635-bc00-8dd93402b7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-rm-container&quot;)</value>
      <webElementGuid>c82dbcb7-d544-43f3-8179-2e28dabd265c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-rm-container']</value>
      <webElementGuid>8879bb2a-99f5-43c2-8e44-5161c8a3a8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-adc']/div[2]/div[13]/div/span/span/span/span</value>
      <webElementGuid>f4fd8a12-8c4d-4f43-a8ec-e9e31e1ba101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/span/span/span/span</value>
      <webElementGuid>d294fd73-136b-43f8-9720-1c8b6549eb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-rm-container' and @title = '--Pilih RM--' and (text() = '--Pilih RM--' or . = '--Pilih RM--')]</value>
      <webElementGuid>cdc19ad3-dc21-40b0-9d40-f792d2c6134c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
