<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_next approver</name>
   <tag></tag>
   <elementGuidId>10e0ee78-1f2b-41df-a1f7-c3ae4957f4f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-NextApprover-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-NextApprover-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5efcc76d-88bb-49dc-a408-ac4803463e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>cc12f574-0d25-42c4-9b7b-f8ef861cc697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-NextApprover-container</value>
      <webElementGuid>65e273f6-d336-4143-8f85-c42b5c2b5b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b3619549-cd8d-4e7a-b69c-2ce841f774c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>efe54741-0526-4e07-acc9-29abd1891b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>f72c43a5-9a0e-420e-945e-c4b3284d1d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>668513de-1c54-4fa9-a8c8-bb111331270d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-NextApprover-container&quot;)</value>
      <webElementGuid>25f15db8-b9ee-43c8-9695-0eb7c44bd887</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-NextApprover-container']</value>
      <webElementGuid>befd3997-180c-4a57-bbcd-00d4548948db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-adc']/div[2]/div[13]/div[2]/div/span/span/span/span</value>
      <webElementGuid>a9415fea-5141-495a-968f-efa4e64caec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/div/span/span/span/span</value>
      <webElementGuid>14576cd0-c92d-4288-8892-ef069cd8dfa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-NextApprover-container' and @title = '-' and (text() = '-' or . = '-')]</value>
      <webElementGuid>408685c8-9e7d-4964-a3fe-4fc7476e11f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
