<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Comment</name>
   <tag></tag>
   <elementGuidId>7129eab4-ac9c-4c41-ba4e-f2200dd77883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Comment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Comment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0bce0d87-7849-47c2-8508-e774c97caa33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>1bcc78bf-01e1-47c9-954e-77941f3b070c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-4</value>
      <webElementGuid>c44fb76c-e477-499a-aabd-c60655d18cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>Comment</value>
      <webElementGuid>9c9f8bfe-64b8-4bf4-8426-012c58d7e5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Comment</value>
      <webElementGuid>409e50ec-b1c5-43d0-8dd5-a16e8348110f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Comment</value>
      <webElementGuid>a9da91d7-9182-44e8-92a8-e42c7b7f2bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Comment&quot;)</value>
      <webElementGuid>770c8f0c-1c44-46f9-a8b3-de72b4387632</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Comment']</value>
      <webElementGuid>b420201a-052f-4ed1-9da3-38eaa9bdf7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-adc']/div[2]/div[13]/div[3]/textarea</value>
      <webElementGuid>dcecad2f-c266-42c2-a553-248081991322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9e8370a9-a613-402a-9cb1-a43bfcc91a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Comment' and @placeholder = 'Add Comment']</value>
      <webElementGuid>5517b4b0-72f6-46c8-9ecd-a80d69aa6a1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
