<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NamaDebitur</name>
   <tag></tag>
   <elementGuidId>ddc12495-0d36-4f07-be08-bbc74370f98a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NamaDebitur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NamaDebitur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0c26bf1-e3f2-4424-9192-399e0b8ebe21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>NamaDebitur</value>
      <webElementGuid>cc7877f4-d492-44fd-b2ba-8d20a49513c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NamaDebitur</value>
      <webElementGuid>bb714179-3c05-4fcc-9195-6d21ddb1f839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NamaDebitur</value>
      <webElementGuid>f79ac267-51c8-4d85-b5a2-2628fbda175f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-4 mt-2</value>
      <webElementGuid>9d9826ab-0679-4fc3-9131-a537efd4a7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Debitur</value>
      <webElementGuid>d3803ce1-10dc-4cad-8ae4-28ff9a794cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8182d38a-b9c5-4ccc-a7e4-b282625d8554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NamaDebitur&quot;)</value>
      <webElementGuid>b2cd2874-87df-419f-ab53-ee804edf0491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NamaDebitur']</value>
      <webElementGuid>70fb7b9e-4c97-4fbd-a66b-8c9c42c5cefe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b4cf0410-0812-4831-b532-530df48e275a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NamaDebitur' and @id = 'NamaDebitur' and @placeholder = 'Nama Debitur']</value>
      <webElementGuid>b7613b79-6c60-41f4-afa7-de127488c8df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
