<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoTestKey</name>
   <tag></tag>
   <elementGuidId>0b7fad73-11e2-4f82-89cc-990473de459f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NoTestKey']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NoTestKey</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9abda86-bbe1-4d2e-9d7a-bb5ea248ec30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>asp-for</name>
      <type>Main</type>
      <value>NoTestKey</value>
      <webElementGuid>74eef556-a070-4422-8eaf-c9636e114977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NoTestKey</value>
      <webElementGuid>2922e8ed-af56-4171-b7c1-b195d3b4c90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NoTestKey</value>
      <webElementGuid>3feb1396-02f6-4276-b5e6-bfa348fb9879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-md-4</value>
      <webElementGuid>18dc8707-d937-46b4-9642-2b787a0c16fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor TestKey</value>
      <webElementGuid>ec3894b0-ed16-4b05-aa30-b79bb650d7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bd8a7f1c-fa84-4f98-879e-db78b3a58669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NoTestKey&quot;)</value>
      <webElementGuid>54c9ed40-f689-4b02-99e9-2a8bc8bff958</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NoTestKey']</value>
      <webElementGuid>327b735f-4d80-4514-a28f-bafce2364232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>a1fbdafa-7430-42a5-912d-1f9e00c19d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'NoTestKey' and @id = 'NoTestKey' and @placeholder = 'Nomor TestKey']</value>
      <webElementGuid>1d9adc60-d1a2-4f05-a8b3-85abdcddd2a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
