<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoPK_Akhir</name>
   <tag></tag>
   <elementGuidId>48c40fa3-ffcf-4e66-9f10-37d6bc1a661a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DetailRateBunga_NoPKAkhir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DetailRateBunga_NoPKAkhir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99c2825f-a16b-4adf-b974-38cc7af44df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>752426cf-35d8-4556-b105-8fc4561a9b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DetailRateBunga_NoPKAkhir</value>
      <webElementGuid>5333b0ba-3ff4-47d4-b4e9-84e4a567aa13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>b14db7b6-adc3-43ff-8b62-2782bbf76a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DetailRateBunga.NoPKAkhir</value>
      <webElementGuid>c25f278c-783d-4b5b-a684-c833739d8aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>134b43e8-c0fb-41e8-9175-2f2c61be127c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NOMORPKAKHIR</value>
      <webElementGuid>f34c8b4c-22ea-4b71-b6f9-62378ea4042c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e77b289e-7b31-4713-b43c-a3a364ce4b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DetailRateBunga_NoPKAkhir&quot;)</value>
      <webElementGuid>bc82dc6d-139f-49bb-b2a0-067e75c75fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DetailRateBunga_NoPKAkhir']</value>
      <webElementGuid>4ec736c4-f17e-45bf-86fe-156f4c994c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormPembukaanRekening']/div/div[8]/div/input[3]</value>
      <webElementGuid>cfa79024-0159-4657-ab92-7dbe91b743c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input[3]</value>
      <webElementGuid>670e3857-3a72-4123-919f-098deb667af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DetailRateBunga_NoPKAkhir' and @name = 'DetailRateBunga.NoPKAkhir' and @type = 'text']</value>
      <webElementGuid>5c6ce501-5ad5-47ad-a8dc-3f72c7922770</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
