<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maksimum Kredit</name>
   <tag></tag>
   <elementGuidId>f99b3797-d1c9-4ff9-8889-0827d8474434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DetailRekening_MaxKredit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DetailRekening_MaxKredit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b9a1c5c-4851-41fb-be40-edbf906423f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control money-tag</value>
      <webElementGuid>46d470ce-4eaa-4708-adc8-308649c5c76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c84068aa-8e20-41ae-a89d-ffc68141bd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field MaxKredit must be a number.</value>
      <webElementGuid>fc0c7083-3ddc-4f9a-ae55-3279e507bedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DetailRekening_MaxKredit</value>
      <webElementGuid>80905e2c-8eb2-45d2-b75d-c22db0c7fac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DetailRekening.MaxKredit</value>
      <webElementGuid>9693e740-d0c4-4bb8-b0f4-71c60d9eeeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a88e7f2-3b77-42a4-af3c-a2793a00548d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d9ba3f3e-5aef-49f5-89f7-3342765ba4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DetailRekening_MaxKredit&quot;)</value>
      <webElementGuid>6e675ba3-006f-47e8-b683-d6b4159b01b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DetailRekening_MaxKredit']</value>
      <webElementGuid>c9a01603-f2b4-4703-a239-c9b625520ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormPembukaanRekening']/div/div[8]/div/input[4]</value>
      <webElementGuid>8b9693f2-e685-4942-9584-81790d4715b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>42d20ae4-9116-4aea-9d1e-f865b6bac7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DetailRekening_MaxKredit' and @name = 'DetailRekening.MaxKredit' and @type = 'text']</value>
      <webElementGuid>1bf77d70-b68d-4991-9ed8-f86743fa7f58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
