<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Rekening Simp_PencairanDana</name>
   <tag></tag>
   <elementGuidId>c6255758-81e4-4a4c-a70b-160732382a19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DetailPencairanDana_Kredit_NoRekening']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DetailPencairanDana_Kredit_NoRekening</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82b61080-b406-490b-bddc-cff4e3b9a461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2de57035-82ee-4863-9d04-4140f1510ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bd38f518-30a8-4a61-bfbe-227e4d090635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NoRekening field is required.</value>
      <webElementGuid>9548b2b1-7131-4f7b-a114-d934adfca8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DetailPencairanDana_Kredit_NoRekening</value>
      <webElementGuid>6c457ae4-111e-45a4-87a8-850adf76f8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DetailPencairanDana_Kredit.NoRekening</value>
      <webElementGuid>693455b7-1218-4331-af50-533c465a3652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ce6a36b-db9b-4c37-b04a-612f4979402d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3202ee1a-0bc5-4304-8857-935d7f61dac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DetailPencairanDana_Kredit_NoRekening&quot;)</value>
      <webElementGuid>3e945960-baa4-4015-bfc4-56c3087198db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DetailPencairanDana_Kredit_NoRekening']</value>
      <webElementGuid>d76c330b-f322-488c-ba23-bcf5c4f6a9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='not_pencairan_rek_bar']/div[2]/input</value>
      <webElementGuid>78f9b5f4-9346-4a39-a035-40eaeb2147b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>27d30ca6-ee82-4294-a91c-9be6d6682272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DetailPencairanDana_Kredit_NoRekening' and @name = 'DetailPencairanDana_Kredit.NoRekening' and @type = 'text']</value>
      <webElementGuid>a9e81780-5862-445d-a655-f1e589f8b3ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
