<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalPK_Awal</name>
   <tag></tag>
   <elementGuidId>5236515b-8ff6-4a07-ad9e-90a016fe69db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DetailRateBunga_TanggalPKAwal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DetailRateBunga_TanggalPKAwal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24d3d6f3-3a4d-4d21-9eb1-1a5f079d9fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>25103370-c0da-4d85-b938-ee69daac730e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#tanggalPkAwalDate</value>
      <webElementGuid>a51f4341-a7ef-49e7-b4f8-7e34efdeced7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DetailRateBunga_TanggalPKAwal</value>
      <webElementGuid>9c790c1a-c469-41e2-9edd-80da90a4f8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DetailRateBunga.TanggalPKAwal</value>
      <webElementGuid>0e8b6c6e-fb55-4d15-830a-d85097559dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>1ba11adb-c66b-4a16-9e5f-2b82c366c898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c2a2733-9b3b-4569-90b0-8ebf5fa49c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>01/04/2025</value>
      <webElementGuid>c845df11-7b5d-4614-af47-fe2a4f045aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dee9666c-eb78-4e6c-a14b-fc8bdc869f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DetailRateBunga_TanggalPKAwal&quot;)</value>
      <webElementGuid>84ce69b4-1f8a-48b6-a5b3-09dd5a00e41a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DetailRateBunga_TanggalPKAwal']</value>
      <webElementGuid>fc54cbc7-b478-40e5-b6d6-a5a638e75980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tanggalPkAwalDate']/input</value>
      <webElementGuid>f3fd20b7-92c3-41d7-a831-ce03c5ac21d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>a1c3df66-e5c4-4a73-aaac-f3530c02eb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DetailRateBunga_TanggalPKAwal' and @name = 'DetailRateBunga.TanggalPKAwal' and @placeholder = 'dd/mm/yyyy' and @type = 'text']</value>
      <webElementGuid>7616e1db-ca68-4085-8f3d-b08cafdb5df4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
