<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoPK_Awal</name>
   <tag></tag>
   <elementGuidId>9164f1f4-f4e9-4c21-8f18-55dd5895b685</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DetailRekening_NoPK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DetailRekening_NoPK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c02899a-eb7f-43aa-8b02-8fc7d3b27fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>535de632-6bc8-4cc0-9c1c-7be23a905f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>417151e0-9782-48b0-b647-fa92e014aec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NoPK field is required.</value>
      <webElementGuid>bcf0f066-fa2c-43d4-9fce-6e436d655ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DetailRekening_NoPK</value>
      <webElementGuid>b71ddeb0-f3a7-4e2d-b595-bdee1094e87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>ce4f6b2d-151a-4f64-b7c0-ac1af1678fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DetailRekening.NoPK</value>
      <webElementGuid>a737294f-62c9-4bc6-8eaa-c04448a44dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d919e7a9-d44a-460d-bc32-c53121c9c76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NOMORPKAWAL</value>
      <webElementGuid>520a3ae8-d1df-44e2-b609-b715c4cb85c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f064abbf-2c5b-49c5-87eb-c17077eee161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DetailRekening_NoPK&quot;)</value>
      <webElementGuid>d463ac83-663b-40ed-b6a7-2bb70a992b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DetailRekening_NoPK']</value>
      <webElementGuid>10af16e3-6c39-4647-ab92-aba544175f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormPembukaanRekening']/div/div[8]/div/input[2]</value>
      <webElementGuid>44bd1253-0741-4ae5-b662-e48a8f3500c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input[2]</value>
      <webElementGuid>1cb3946f-c60a-41a2-ac5e-54fbfbb204c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DetailRekening_NoPK' and @name = 'DetailRekening.NoPK' and @type = 'text']</value>
      <webElementGuid>049b9fc2-9370-40d9-a81d-52dbfb2dc9a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
