<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalPK_Akhir</name>
   <tag></tag>
   <elementGuidId>152ebc1e-b563-4c22-84f6-d4c048bd53d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DetailRateBunga_TanggalPKAkhir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DetailRateBunga_TanggalPKAkhir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7ca11a2-4bbd-4813-a922-ce93842bcdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>0ac71a62-06a0-4186-8311-3ddb2d2eb1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#tanggalPkAkhirDate</value>
      <webElementGuid>f2b9996f-78b9-47e7-b70e-3aac2463b43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DetailRateBunga_TanggalPKAkhir</value>
      <webElementGuid>619ae545-0b86-4ca2-8778-1ad011ad8d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DetailRateBunga.TanggalPKAkhir</value>
      <webElementGuid>661d1ec4-032d-4daf-a562-cb2e36fde3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>28cefd1e-6c87-4df2-9eeb-e2b572069426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4160b96d-390d-4019-b6de-ffa868c32bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>08/05/2025</value>
      <webElementGuid>9dbd112b-ffea-4781-b502-f23e805e1de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bc3ace42-f9f9-4bed-96cd-88ba63e02097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DetailRateBunga_TanggalPKAkhir&quot;)</value>
      <webElementGuid>05a7705d-ed1a-437c-accf-04ba1a9e856a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DetailRateBunga_TanggalPKAkhir']</value>
      <webElementGuid>533e947e-dede-4599-8556-348ee1662419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tanggalPkAkhirDate']/input</value>
      <webElementGuid>73bcbc77-faa1-40e1-9ba9-caf96bcdc8da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>48fa0478-2a65-46dc-96af-ccf752fe5127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DetailRateBunga_TanggalPKAkhir' and @name = 'DetailRateBunga.TanggalPKAkhir' and @placeholder = 'dd/mm/yyyy' and @type = 'text']</value>
      <webElementGuid>cf2e48f3-ccb3-4ad5-8a6b-b5b099ee57b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
