<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal_Pencairan Dana</name>
   <tag></tag>
   <elementGuidId>2177ef2b-39ec-41d0-8624-74670577309b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DetailPencairanDana_Debit_Nominal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DetailPencairanDana_Debit_Nominal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8458f0ab-4bc9-451f-b75a-b06561c12417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control money-tag</value>
      <webElementGuid>78df96a9-23b2-4df7-a6af-d30f0e4c2bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8363ba98-82b8-45c8-8912-81a313c79078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Nominal must be a number.</value>
      <webElementGuid>da4b45ab-630b-4475-b8f5-d857d3ce2385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DetailPencairanDana_Debit_Nominal</value>
      <webElementGuid>837d5113-77c8-48ed-8ec6-c4c72ba1870e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DetailPencairanDana_Debit.Nominal</value>
      <webElementGuid>5fb7ebd2-7549-42e0-890f-a0abc7eb7e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ValidasiNominalDebitKredit();</value>
      <webElementGuid>d1b13a2c-b8b4-47a5-913b-8b2064191f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de086873-1057-4b2e-b403-941734760239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5c61684e-e386-4d84-b3ac-5629f7f71129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DetailPencairanDana_Debit_Nominal&quot;)</value>
      <webElementGuid>f77bc2c7-0691-4547-8396-527f623c2cee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DetailPencairanDana_Debit_Nominal']</value>
      <webElementGuid>d6dbfbd2-9e95-44fb-b633-2d03df750452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='not_pencairan_rek_bar']/div/input[5]</value>
      <webElementGuid>725f9935-b4fc-47f0-9f01-4c43764f0952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[5]</value>
      <webElementGuid>8b9881a9-f8dc-446f-b468-8f9ece603248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DetailPencairanDana_Debit_Nominal' and @name = 'DetailPencairanDana_Debit.Nominal' and @type = 'text']</value>
      <webElementGuid>bb3b200e-9b9e-4c66-b8d2-71dbf67ee760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
