<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_0701Efektif IDR</name>
   <tag></tag>
   <elementGuidId>9350c915-b745-4a05-99fb-a8a4be5a985b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-DetailRekening_SubKategori-result-svet-0701:Efektif IDR']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5f68dfee-25aa-4e47-9498-e593052fba29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>3a0e67b3-5cdf-48d4-a9cb-89621c43d6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-DetailRekening_SubKategori-result-svet-0701:Efektif IDR</value>
      <webElementGuid>14f0f31e-3c17-4b65-badc-f075a26c15c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b938cc45-9ddf-4cef-a947-c5ac20588529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1c51441c-cacb-4a0e-bd3a-e1579a152330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-DetailRekening_SubKategori-result-svet-0701:Efektif IDR</value>
      <webElementGuid>dc2d5f80-609e-41ce-b420-c11af66aa12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0701:Efektif IDR</value>
      <webElementGuid>72a4056b-6f5e-42ea-9704-a04e75f2255e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-DetailRekening_SubKategori-result-svet-0701:Efektif IDR&quot;)</value>
      <webElementGuid>0c6c4ceb-9381-47cb-bd4a-abc27f5055c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-DetailRekening_SubKategori-result-svet-0701:Efektif IDR']</value>
      <webElementGuid>9a0c1247-4369-4a47-8416-e79eaab54e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-DetailRekening_SubKategori-results']/li[2]</value>
      <webElementGuid>3911df7d-9a78-459d-abb7-d31e3eefe4ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[2]</value>
      <webElementGuid>d7aff19e-a969-42e7-b514-904a964f730b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-DetailRekening_SubKategori-result-svet-0701:Efektif IDR' and (text() = '0701:Efektif IDR' or . = '0701:Efektif IDR')]</value>
      <webElementGuid>5074d4a9-59be-42bb-b08d-adf9b17ded3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
