<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sub Kategori</name>
   <tag></tag>
   <elementGuidId>f27688fd-7b1f-4830-a71b-9e0ee7c52497</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-DetailRekening_SubKategori-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-DetailRekening_SubKategori-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9cbb5373-47f0-44ec-93f9-796cf23b748c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>9a618188-557d-4f1e-ba85-27047d18d931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-DetailRekening_SubKategori-container</value>
      <webElementGuid>b214129d-cd7d-4c10-b992-7221a4540093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>acbba3e3-3333-43f9-a1f6-6942d5411d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c6b2307-911a-47e7-aa4e-2ea4f6524f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>176e3702-5684-4f54-86f7-7699c9213eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>1ef382e6-b0e3-4177-a3a8-dfce13afb358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-DetailRekening_SubKategori-container&quot;)</value>
      <webElementGuid>0e32ccf9-8747-49a8-9a88-ff301aac55a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-DetailRekening_SubKategori-container']</value>
      <webElementGuid>f792687c-3a02-4e87-8982-7564d1059ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormPembukaanRekening']/div/div[8]/div[2]/span[2]/span/span/span</value>
      <webElementGuid>5e792fb3-da46-43a2-80c6-03efade1901c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]/span/span/span</value>
      <webElementGuid>bd68e66d-6fa1-4066-ad0e-e336f7822ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-DetailRekening_SubKategori-container' and @title = '-' and (text() = '-' or . = '-')]</value>
      <webElementGuid>35cc3333-6286-4ea5-aa8e-4fb06ebbb209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
