<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cabang Pembuka</name>
   <tag></tag>
   <elementGuidId>0272bf1d-71ac-437a-adae-656305d62ddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-DetailRekening_Cabang-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-DetailRekening_Cabang-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9202dd91-f428-479c-8d41-f2cfba057670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>88727cdb-7da6-45ff-8872-0cc77cab7b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-DetailRekening_Cabang-container</value>
      <webElementGuid>7c8af198-7af9-4972-a6d6-c83dec3f75ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>6f45de39-8a25-484f-95e1-a5b0827bbc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b278cd1-a83b-4bde-966a-d845de8ee0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>360f9f1f-769b-4bc8-9ade-e37dc1382f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>0490a3fb-70c5-451e-b008-52bc41c9f94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-DetailRekening_Cabang-container&quot;)</value>
      <webElementGuid>bc36ac78-971c-4335-924b-518f649047ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-DetailRekening_Cabang-container']</value>
      <webElementGuid>6114ceb0-d3b0-4dab-86e1-db9ab202d779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AddEditFormPembukaanRekening']/div/div[8]/div/span/span/span/span</value>
      <webElementGuid>2f530a06-51c5-472e-864d-70fbdbdfca67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>8b55a21d-9c7c-40b2-bb71-9a2cc35d8ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-DetailRekening_Cabang-container' and @title = '-' and (text() = '-' or . = '-')]</value>
      <webElementGuid>3d9f5bd5-5c6a-43ac-bd3e-e61166cf9b95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
