<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Narasi PencairanDana</name>
   <tag></tag>
   <elementGuidId>f3a2e19f-7474-4959-a194-d85daa420045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='PencairanDana_Detail_Narasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PencairanDana_Detail_Narasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d0c3b4c8-00c7-4db3-a1b3-1bf5d66df809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e15541ff-ef89-43ff-9cf3-5e7dbc30bfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c24db0f9-4eb8-4c05-96b7-2d9ed0ecd149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Narasi field is required.</value>
      <webElementGuid>7f99779f-1943-45c9-9cb6-c9d094001df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PencairanDana_Detail_Narasi</value>
      <webElementGuid>ed435562-3f63-4af2-b829-e113467ed573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e8ef4f28-5545-45e6-a5a9-ab0df720f42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PencairanDana_Detail.Narasi</value>
      <webElementGuid>e1adcab2-e767-412e-987d-52edde301b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PencairanDana_Detail_Narasi&quot;)</value>
      <webElementGuid>1775b411-e447-41e1-953d-5fd9d1292908</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='PencairanDana_Detail_Narasi']</value>
      <webElementGuid>ab550daf-3db0-4870-8a51-69ee2c991a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='not_pencairan_rek_bar']/div[3]/textarea</value>
      <webElementGuid>e956a762-8a27-4a37-af37-6f86f5e9f456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c9f9aa6b-3f39-447f-a4e6-2f23cc2090d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'PencairanDana_Detail_Narasi' and @name = 'PencairanDana_Detail.Narasi']</value>
      <webElementGuid>2e966902-d6eb-47b8-be18-408606055303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
