<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Narasi Tambahan_PencairanDana</name>
   <tag></tag>
   <elementGuidId>404da445-3e4c-47b1-bf8a-40ba4457d2b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='PencairanDana_Detail_NarasiTambahan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PencairanDana_Detail_NarasiTambahan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bc3160b9-b598-49ad-b388-46e3ca819320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a6bc4166-87f3-40e4-a437-2f8c4b151bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3654ac2d-684e-45d7-b580-03a9c08e5977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The NarasiTambahan field is required.</value>
      <webElementGuid>c45c9c00-ad08-4ed8-b048-d6be19017c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PencairanDana_Detail_NarasiTambahan</value>
      <webElementGuid>231d87e4-ab8b-40c7-a2ee-05a1332021b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b23a6ffd-d5ce-471d-a77f-9246210887d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PencairanDana_Detail.NarasiTambahan</value>
      <webElementGuid>ab8efd13-c840-4dfa-a764-24a73f642b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PencairanDana_Detail_NarasiTambahan&quot;)</value>
      <webElementGuid>0fdf3b2e-9013-4287-a151-76528ba77802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='PencairanDana_Detail_NarasiTambahan']</value>
      <webElementGuid>19911f11-bf09-4b57-a2c3-0e4c0b2b4640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='not_pencairan_rek_bar']/div[3]/textarea[2]</value>
      <webElementGuid>a3555e87-9209-4d0c-9d9c-d4a3e03c70c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea[2]</value>
      <webElementGuid>dfa2daa7-94c7-4974-a25a-f2bea131c217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'PencairanDana_Detail_NarasiTambahan' and @name = 'PencairanDana_Detail.NarasiTambahan']</value>
      <webElementGuid>4a63a171-a2e3-47cf-9d4e-26a45f0d0be2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
