<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_MaksimumPinjaman</name>
   <tag></tag>
   <elementGuidId>d48ba1e7-36fc-4670-ada5-3e0972a13473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#HasMaksimumPinjaman</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='HasMaksimumPinjaman']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19ed1f9a-8d3e-4df4-a0f9-f1af66b933e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>38a66f45-ea20-409e-9e2f-4474d996afe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ec5c4704-77ae-4800-a05c-609d3c34bdc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The HasMaksimumPinjaman field is required.</value>
      <webElementGuid>4766fe72-c425-45a6-a310-9dd5bc3d3011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>HasMaksimumPinjaman</value>
      <webElementGuid>de58a173-d6e2-4a2c-91d7-4daf419d0578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>HasMaksimumPinjaman</value>
      <webElementGuid>113a480a-bacb-42cc-9b66-c3bac9496025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CheckMaksimumForm()</value>
      <webElementGuid>271f0908-bd53-47b5-b6b4-9cebf62ee103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>11f0e7ad-69f4-48c1-b398-eec08d610cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1aa8710b-6d1f-421c-bb02-6f1a93c0a329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e706f4fe-1440-4759-8cea-1036f9edc8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HasMaksimumPinjaman&quot;)</value>
      <webElementGuid>7f6ec6ad-a828-4a05-aeee-2eec119a7bde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='HasMaksimumPinjaman']</value>
      <webElementGuid>723a271c-d215-4115-a276-0c615d0036f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='maksimumPinjamanTable']/tbody/tr/td/input</value>
      <webElementGuid>66ccefe2-c3b4-47d3-ab40-b847adc010fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[5]/tbody/tr/td/input</value>
      <webElementGuid>eef42d97-4c67-418e-8ee3-a77d5b701e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'HasMaksimumPinjaman' and @name = 'HasMaksimumPinjaman' and @type = 'checkbox']</value>
      <webElementGuid>0b6aff1c-e8c5-4fe4-9ab8-bb920a18ba6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
