<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_PosisiRek_RekeningAfiliasi</name>
   <tag></tag>
   <elementGuidId>3af7c439-c725-4be2-bd2d-781ecf1bcc30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PosisiRekeningAfiliasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PosisiRekeningAfiliasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93f0ac46-9d76-475b-a047-a1a90ce01703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ec639c72-dea7-4339-b9db-cc7a710f11ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PosisiRekeningAfiliasi</value>
      <webElementGuid>3c05d06a-2b0f-419d-b746-4988d6f3fb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PosisiRekeningAfiliasi</value>
      <webElementGuid>733b400e-3178-46e7-b7a6-58537b8fd699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CheckPosisiRekening()</value>
      <webElementGuid>72c4f838-4eb6-4fdb-aecc-148aef245657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>32710de5-28a6-4c06-820d-0451ad4c4dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9faca177-6f72-4e6d-8526-246e7e2d22db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f63d10af-1cf0-4aad-b450-9a9fb6b62d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PosisiRekeningAfiliasi&quot;)</value>
      <webElementGuid>bd6f56b6-551e-4eb7-9389-f2b753a45cbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PosisiRekeningAfiliasi']</value>
      <webElementGuid>774a399e-1791-45ee-a253-3d5f126d3fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='posisiRekeningTable']/tbody/tr[2]/td/input</value>
      <webElementGuid>2041d800-5ff0-4874-a553-90e3401e6edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>b051d7b5-00df-4f07-bd24-bdcc8dacd546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PosisiRekeningAfiliasi' and @name = 'PosisiRekeningAfiliasi' and @type = 'checkbox']</value>
      <webElementGuid>799fbc0e-99bf-4be1-9805-511ca3a1a7c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
