<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_PosisiRek_RateBunga</name>
   <tag></tag>
   <elementGuidId>f21c8813-3135-4cbe-9e12-d7764dc6662f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PosisiRekeningRate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PosisiRekeningRate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f55c08f4-b5f3-4583-b1f1-06877c8e0097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a4bb9ef8-bff3-4d80-ba0d-76e52163a4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PosisiRekeningRate</value>
      <webElementGuid>a941b5f3-095d-4f0e-86d0-90e9792a63fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PosisiRekeningRate</value>
      <webElementGuid>ac837bdd-ea97-48aa-b749-f94271df96e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CheckPosisiRekening()</value>
      <webElementGuid>9d437c43-7215-4ed2-883f-31f79adfb591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4b29b4e7-26e6-4efa-81a2-64c43a4d1219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>daacc13e-7709-45de-a8ae-fe18967f22f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>876bfd4e-452a-4fa4-89c4-55e52e0d34a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PosisiRekeningRate&quot;)</value>
      <webElementGuid>d840f750-8a31-4011-95dd-b0207001dde6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PosisiRekeningRate']</value>
      <webElementGuid>6c0df9e4-bf53-444e-a276-a26184acbba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='posisiRekeningTable']/tbody/tr[3]/td/input</value>
      <webElementGuid>f457f3c5-3f52-43f5-a12d-fbbbf73d17bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>dc2bf706-8e0b-452e-82a2-659e89caa100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PosisiRekeningRate' and @name = 'PosisiRekeningRate' and @type = 'checkbox']</value>
      <webElementGuid>a77b0acb-d617-4794-af2d-8b8566cc4594</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
