<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_JatuhTempo</name>
   <tag></tag>
   <elementGuidId>b2b3d36b-c413-45b5-9425-feec982f2903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='HasJatuhTempo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#HasJatuhTempo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe9bca6f-a036-429d-8494-15147217241b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>40c28885-d7f7-4ccb-b655-5db3bff4be67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>da9a3c56-130f-41dc-94ef-0dd65a707e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The HasJatuhTempo field is required.</value>
      <webElementGuid>2cde58d4-a1ea-4ead-96d9-e4a665f4cf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>HasJatuhTempo</value>
      <webElementGuid>7e043680-b882-422d-bcfc-462aa9783a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>HasJatuhTempo</value>
      <webElementGuid>342cfbf4-d6c3-4299-bae4-c79288340fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CheckJatuhTempoForm()</value>
      <webElementGuid>76ff6cc7-8c4b-444c-9edb-07b800bd9dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ff995ab7-edb0-41bc-ba0a-dc72acc56ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d5a8885-f573-4df6-9b8b-3aaf97e46986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>12256808-7653-4f30-95c1-64128dc31d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HasJatuhTempo&quot;)</value>
      <webElementGuid>8b65c9ce-cd8d-44f8-b3eb-2249aedd2be9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='HasJatuhTempo']</value>
      <webElementGuid>3d014b2e-5cf8-4fb2-90d7-2bac6f7a429d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='jatuhTempoTable']/tbody/tr/td/input</value>
      <webElementGuid>b25236a4-df52-411c-93d4-6159e123b5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr/td/input</value>
      <webElementGuid>e10d4919-5ca8-47fe-8f5c-d880cd096c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'HasJatuhTempo' and @name = 'HasJatuhTempo' and @type = 'checkbox']</value>
      <webElementGuid>9b8b3667-5239-48fe-8aef-a4794ea5981f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
