<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PosisiRek_Rekening Afiliasi_Menjadi</name>
   <tag></tag>
   <elementGuidId>923d9a44-6bbb-4764-8cb1-c59ad527686b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PosisiRekening_RekeningAfiliasiResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PosisiRekening_RekeningAfiliasiResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a4eb530-6e15-4eae-8fda-65b91683f3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>da3a9daa-6629-434f-98d3-1e0d9fd9dfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9ecc077b-5eae-447f-9f99-85f720ce5213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RekeningAfiliasiResult field is required.</value>
      <webElementGuid>f8c19732-0a2d-4305-854c-b61990672237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PosisiRekening_RekeningAfiliasiResult</value>
      <webElementGuid>ef0ec8e2-0491-491d-a3f9-2589d259010f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PosisiRekening.RekeningAfiliasiResult</value>
      <webElementGuid>7f3d1f36-2e77-4665-b05d-61925bb2f63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rekening Afiliasi Menjadi</value>
      <webElementGuid>8d328278-2377-4963-9224-c50031d2305c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8f2c780-42a8-4a46-aea4-ed553494c477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>41b53a57-24fb-49e6-85e6-355ed3acb7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PosisiRekening_RekeningAfiliasiResult&quot;)</value>
      <webElementGuid>35b3cf5a-0d73-4f6b-ab5f-35632dc43458</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PosisiRekening_RekeningAfiliasiResult']</value>
      <webElementGuid>8abc3b4c-1f01-4c0c-a0fa-162fc3882d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='posisiRekeningTable']/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>db06c8e1-5455-48fd-abb3-07cf55a3a5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>6af56364-a2f3-4e5c-a8d5-ed07fd45528d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PosisiRekening_RekeningAfiliasiResult' and @name = 'PosisiRekening.RekeningAfiliasiResult' and @placeholder = 'Rekening Afiliasi Menjadi' and @type = 'text']</value>
      <webElementGuid>5185f8a1-e47f-4729-a624-99cb68c5c6c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
