<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal PK Akhir Menjadi</name>
   <tag></tag>
   <elementGuidId>b6dbb17a-52a6-45b5-9e39-7b8aaece15a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='JatuhTempo_TanggalPkAkhirResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#JatuhTempo_TanggalPkAkhirResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5af8f9a7-c7ca-412d-8fea-33b80f818b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>3a4140fb-df88-4bc4-8fba-b1fda19d25db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#tanggalPkAkhirDate</value>
      <webElementGuid>b2876ecf-83a2-4f81-bed3-332ed08f13dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JatuhTempo_TanggalPkAkhirResult</value>
      <webElementGuid>5c1f1b59-67d9-4b7a-a64b-a1c587752aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JatuhTempo.TanggalPkAkhirResult</value>
      <webElementGuid>64352424-f8a9-4ee6-a075-26fe7d5cdc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>d2e15723-ebe4-4fdc-af43-d6a93c0526b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f5bbc15-9415-44bc-8ef3-16feaee46cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f38f3553-0bfb-4923-ac14-49475b661b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JatuhTempo_TanggalPkAkhirResult&quot;)</value>
      <webElementGuid>c410223f-095f-48c1-a8ab-543a24ae1167</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='JatuhTempo_TanggalPkAkhirResult']</value>
      <webElementGuid>4537917a-707b-459a-81ca-287689531a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tanggalPkAkhirDate']/input</value>
      <webElementGuid>381df7df-e059-4b4e-aedf-1c126db9a242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[4]/div/input</value>
      <webElementGuid>227eed67-6e10-49a3-bad5-afc1ce0b60ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'JatuhTempo_TanggalPkAkhirResult' and @name = 'JatuhTempo.TanggalPkAkhirResult' and @placeholder = 'dd/mm/yyyy' and @type = 'text']</value>
      <webElementGuid>17ddeab0-c46f-449a-877a-15b4769965c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
