<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor PK Awal Menjadi</name>
   <tag></tag>
   <elementGuidId>e84a023a-2778-4b12-98fd-98ee7e8e06a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='JatuhTempo_NomorPkAwalResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#JatuhTempo_NomorPkAwalResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da02eab9-638d-4ab3-985d-ba3ce28cffdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>91440e6e-9721-4502-863d-81b24a1df9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JatuhTempo_NomorPkAwalResult</value>
      <webElementGuid>b338716a-3060-4df1-ba98-58be11df2041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>a63d8b5f-473d-4f09-9b14-cc68e45fa3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JatuhTempo.NomorPkAwalResult</value>
      <webElementGuid>3bd68a9f-bcd0-4e90-aa88-09b08f6ba29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor PK Awal</value>
      <webElementGuid>b13a1739-2652-4a79-beb4-ccdd84f360c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>222c3103-3aa8-4342-8733-e739309bb81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>182479f7-72e0-43c3-8e74-bd7a1e529b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JatuhTempo_NomorPkAwalResult&quot;)</value>
      <webElementGuid>ee909b55-42fa-49b7-b862-4f5e44ce204c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='JatuhTempo_NomorPkAwalResult']</value>
      <webElementGuid>bfec4caf-77c7-4864-a17e-79f44c9507e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='jatuhTempoTable']/tbody/tr[3]/td[4]/input</value>
      <webElementGuid>c11f93ea-3f5a-4bc6-8033-6c4336011210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/input</value>
      <webElementGuid>dfd59569-41e7-44b0-a524-d3b8f0015332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'JatuhTempo_NomorPkAwalResult' and @name = 'JatuhTempo.NomorPkAwalResult' and @placeholder = 'Nomor PK Awal' and @type = 'text']</value>
      <webElementGuid>92b6fe62-81c5-4bab-b8c8-c8121d45c761</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
