<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal PK Awal Menjadi</name>
   <tag></tag>
   <elementGuidId>c2e0cc9e-dfa8-402e-b16d-ba96e5b2ea54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='JatuhTempo_TanggalPkAwalResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#JatuhTempo_TanggalPkAwalResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86148f8a-e58a-494a-b5ea-bda7043c9fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>86aebf46-9259-419a-bb29-3e6ee5ed5a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#tanggalPkAwalDate</value>
      <webElementGuid>c28cb226-3686-43fd-87d5-d4e89c92f40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JatuhTempo_TanggalPkAwalResult</value>
      <webElementGuid>b56bb379-ee77-4502-a458-4005fd87f9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JatuhTempo.TanggalPkAwalResult</value>
      <webElementGuid>b5dc28bd-679f-4361-90f4-4785f647b16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>9e8e5f06-2f34-45dc-af56-66aa649fa839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d56dec33-65d9-4b8b-acd6-7baddbbda4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>36e720f4-c236-4379-b5ef-d8f36c49556c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JatuhTempo_TanggalPkAwalResult&quot;)</value>
      <webElementGuid>114038bf-676b-41b0-8f94-c1c0964189a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='JatuhTempo_TanggalPkAwalResult']</value>
      <webElementGuid>f663d1e6-22d0-4989-8383-ecb8ee2c1e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tanggalPkAwalDate']/input</value>
      <webElementGuid>04f677b3-4166-4d44-a0ae-9c47a331b308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/div/input</value>
      <webElementGuid>0ec45b13-0a7a-44bd-9b5a-ab99e2fe0a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'JatuhTempo_TanggalPkAwalResult' and @name = 'JatuhTempo.TanggalPkAwalResult' and @placeholder = 'dd/mm/yyyy' and @type = 'text']</value>
      <webElementGuid>0975eb2d-9778-4e10-ad96-23c631f71cd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
