<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_JatuhTempo_Perpanjangan Sementara</name>
   <tag></tag>
   <elementGuidId>e2e734cd-ee68-4d13-a3b9-8bd68b0fd681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='JatuhTempo_PerpanjanganSementaraResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#JatuhTempo_PerpanjanganSementaraResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c40e5460-322f-4114-bb54-0608169867d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inputnumeric</value>
      <webElementGuid>21dfbe26-cdbb-41a7-bf64-9c0e82d6085f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JatuhTempo_PerpanjanganSementaraResult</value>
      <webElementGuid>902cf1b5-fff1-420f-b5f9-3a6e79ed382c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f21c05c2-001f-41bc-8bdf-70e6cdf1a820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JatuhTempo.PerpanjanganSementaraResult</value>
      <webElementGuid>b8f3816d-1e3c-40ea-8515-ceb6864e781a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f93f7c01-28a6-4c0f-87f8-ed8b54b00590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>93f33271-807e-43b6-8179-e5b0eb89b12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JatuhTempo_PerpanjanganSementaraResult&quot;)</value>
      <webElementGuid>dbec2860-5ca2-4cbc-9602-24e30f479c73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='JatuhTempo_PerpanjanganSementaraResult']</value>
      <webElementGuid>d2d8efc0-af22-4588-91c3-584bf5be5361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='jatuhTempoTable']/tbody/tr[7]/td[4]/input</value>
      <webElementGuid>df438c2a-1740-4a22-9169-b7731596cddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[4]/input</value>
      <webElementGuid>417d2428-92c1-40fa-923c-9918194ccd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'JatuhTempo_PerpanjanganSementaraResult' and @name = 'JatuhTempo.PerpanjanganSementaraResult' and @type = 'text']</value>
      <webElementGuid>9633a110-d4fd-499d-8352-834c0439a3d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
