<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PeriodeKapitalisasi_HariPembayaran_Menjadi</name>
   <tag></tag>
   <elementGuidId>9eecc242-7eb5-4a21-a4d3-b21e2a349673</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Kapitalisasi_HariPembayaranResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Kapitalisasi_HariPembayaranResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4e98358-1aa9-42be-afa4-487b2e4c34ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inputnumeric</value>
      <webElementGuid>06bd1be1-1063-4565-bf1d-4da6f9f7cb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kapitalisasi_HariPembayaranResult</value>
      <webElementGuid>93fc5f3f-f006-4903-b543-98192a4b3981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kapitalisasi.HariPembayaranResult</value>
      <webElementGuid>78a95879-27cd-4194-9088-36c020db8f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e525336-1265-453a-870b-13e56845a6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0d5b3530-1050-4d81-ac8a-01c7e03f018e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kapitalisasi_HariPembayaranResult&quot;)</value>
      <webElementGuid>d66aaa85-84b7-4ee7-b1fb-d95d5032903c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Kapitalisasi_HariPembayaranResult']</value>
      <webElementGuid>7d7b4d70-4641-46ed-83dc-f5c3b3176453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kapitalisasiTable']/tbody/tr[4]/td[4]/input</value>
      <webElementGuid>0fb56ee5-7774-449d-83bd-936ba8142595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[4]/td[4]/input</value>
      <webElementGuid>6b3e2c1f-5660-4311-a489-bbffb879d422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Kapitalisasi_HariPembayaranResult' and @name = 'Kapitalisasi.HariPembayaranResult' and @type = 'text']</value>
      <webElementGuid>c372a6f2-8aca-494f-8c1e-de9e3fec0fce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
