<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PeriodeKapitalisasi_TanggalMulaiKapitalisasi_Menjadi</name>
   <tag></tag>
   <elementGuidId>27019d9b-ad4b-4cb1-8725-ec81841a423d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Kapitalisasi_TanggalMulaiResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Kapitalisasi_TanggalMulaiResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f3d2f45-e0f8-4921-ba2a-befabb455e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker hasDatepicker</value>
      <webElementGuid>27f89d84-805f-4152-9f15-4803427aabc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#tanggalMulaiResultDate</value>
      <webElementGuid>3da4c19f-6cb3-4d40-9274-f4d5626dc056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>92d5ffd2-5d39-42cb-b7d1-66a67d452d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The TanggalMulaiResult field is required.</value>
      <webElementGuid>becc1e6d-383a-433c-b69f-00e27b8a1299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kapitalisasi_TanggalMulaiResult</value>
      <webElementGuid>8b1e8c25-da19-4d58-9be0-4d03899989f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kapitalisasi.TanggalMulaiResult</value>
      <webElementGuid>39601152-ee74-466f-b5dd-289ac9f96fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64d5b13d-7ea0-49df-a66a-a3b85728dac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>67f990e7-9e13-4608-978a-eaab927e0bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kapitalisasi_TanggalMulaiResult&quot;)</value>
      <webElementGuid>074afd3d-b0d1-445a-b666-c506a988e6eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Kapitalisasi_TanggalMulaiResult']</value>
      <webElementGuid>3d7fa765-0fdd-4404-a763-43605ea018a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tanggalMulaiResultDate']/input</value>
      <webElementGuid>23c74ed2-773f-4783-9d2d-6237da34dfe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[3]/td[4]/div/input</value>
      <webElementGuid>db85de33-fdac-4872-bb66-3818c38783f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Kapitalisasi_TanggalMulaiResult' and @name = 'Kapitalisasi.TanggalMulaiResult' and @type = 'text']</value>
      <webElementGuid>d8805e13-9b56-42af-9fbc-83b6c145968a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
