<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor PK Akhir Menjadi</name>
   <tag></tag>
   <elementGuidId>58826028-3246-4df5-ac99-14296bfe2062</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='JatuhTempo_NomorPkAkhirResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#JatuhTempo_NomorPkAkhirResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da3646b4-8a1c-46d3-a77d-c4e8513b7956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2274cf86-8ae0-44f7-8be5-d201f356cd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JatuhTempo_NomorPkAkhirResult</value>
      <webElementGuid>6944d78c-acd3-4eb6-bca6-b9dac4f243c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>cc44444a-1acd-420f-b7c8-35f436c44e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JatuhTempo.NomorPkAkhirResult</value>
      <webElementGuid>38fe6685-b787-47e5-beb2-ed30cf2a9344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor PK Akhir</value>
      <webElementGuid>bfd40063-aa89-4622-9c29-84e302701c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>954638b1-1bca-4edc-89e0-129c92862d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f3040311-f5c6-4157-a5e4-7e5f452ac5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JatuhTempo_NomorPkAkhirResult&quot;)</value>
      <webElementGuid>97fc0155-b85c-4ac8-8e01-fab4131793f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='JatuhTempo_NomorPkAkhirResult']</value>
      <webElementGuid>974a9eb6-defc-4b08-85f1-2dc1b006bc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='jatuhTempoTable']/tbody/tr[4]/td[4]/input</value>
      <webElementGuid>d8188d6d-ef82-42e2-9023-df17fa563dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr[4]/td[4]/input</value>
      <webElementGuid>48f49103-74a3-4e3a-8081-cb81a791204e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'JatuhTempo_NomorPkAkhirResult' and @name = 'JatuhTempo.NomorPkAkhirResult' and @placeholder = 'Nomor PK Akhir' and @type = 'text']</value>
      <webElementGuid>9cced61d-0909-4cfb-ae6b-e60b7a1991fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
