<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PeriodeKapitalisasi_TanggalKapitalisasi_Menjadi</name>
   <tag></tag>
   <elementGuidId>8375086d-46e8-448b-99e0-a72fe7a69503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Kapitalisasi_TanggalKapitalisasiResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Kapitalisasi_TanggalKapitalisasiResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66c49ac6-d938-4d9d-a582-b794bc33e9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inputnumeric</value>
      <webElementGuid>8d58ad2d-7da6-4377-9e83-9453642d3f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kapitalisasi_TanggalKapitalisasiResult</value>
      <webElementGuid>877418c1-d0a7-45ee-99b5-b1ab6d722ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kapitalisasi.TanggalKapitalisasiResult</value>
      <webElementGuid>468f7180-efc8-46c6-afa6-67a0f0b7b550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b01d0b9b-bbb9-4ebf-8a3b-17c57d157be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>84031ef9-9b0f-42c8-a6cd-c3833c6c4c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kapitalisasi_TanggalKapitalisasiResult&quot;)</value>
      <webElementGuid>176b41fb-4be3-4d8f-9185-db7817cd8a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Kapitalisasi_TanggalKapitalisasiResult']</value>
      <webElementGuid>b5df00e4-e129-41f4-b125-14c4cfa308d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kapitalisasiTable']/tbody/tr[5]/td[4]/input</value>
      <webElementGuid>71d3f4ca-2768-4c37-8514-7a85b0874db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/input</value>
      <webElementGuid>b4ae6f43-c1a7-4102-9a1d-89e0bc255b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Kapitalisasi_TanggalKapitalisasiResult' and @name = 'Kapitalisasi.TanggalKapitalisasiResult' and @type = 'text']</value>
      <webElementGuid>0f7102c6-c422-44d4-80a8-81e2321b5f5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
