<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maksimum Rekening</name>
   <tag></tag>
   <elementGuidId>62c8bb99-c922-4f68-a7bd-6871c33610b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MaksimumPinjaman_MaksimumRekeningResult</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MaksimumPinjaman_MaksimumRekeningResult']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fb595d7-88e0-4553-8eff-379d5a457a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control nominal</value>
      <webElementGuid>af2eb8fb-9596-453f-82e3-f6b96428025b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>16e97b6a-3107-4b05-a9b4-5f554b23ad72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field MaksimumRekeningResult must be a number.</value>
      <webElementGuid>6c256390-2a19-4b69-891d-7f234da72ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MaksimumPinjaman_MaksimumRekeningResult</value>
      <webElementGuid>536ace14-f72e-440c-ad72-21498893db07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MaksimumPinjaman.MaksimumRekeningResult</value>
      <webElementGuid>baed11b1-af46-4771-ab0d-9efc9c6c5600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Maksimum Rekening Menjadi</value>
      <webElementGuid>3b217d7f-dac9-4076-921c-a1e2ab9ad9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>962a60a7-1cce-4939-9756-4afe67e97c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>815df889-2897-43f9-b0a3-9c31d8fe0dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MaksimumPinjaman_MaksimumRekeningResult&quot;)</value>
      <webElementGuid>c2a7b64a-995f-4963-8677-b04bc57c21a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MaksimumPinjaman_MaksimumRekeningResult']</value>
      <webElementGuid>990250fe-e30a-45b0-823b-7381b6561a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='maksimumPinjamanTable']/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>a7773820-8290-4f1d-8b8c-cd9d6cf090d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[5]/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>9417baf9-ae58-4cf2-88a3-41d86e8d5c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MaksimumPinjaman_MaksimumRekeningResult' and @name = 'MaksimumPinjaman.MaksimumRekeningResult' and @placeholder = 'Maksimum Rekening Menjadi' and @type = 'text']</value>
      <webElementGuid>e37ce01a-bd2d-4452-ac39-7306604e24a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
