<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PosisiRek_RateBunga_Menjadi</name>
   <tag></tag>
   <elementGuidId>f3742dde-53fe-4b9c-a96f-1909b48fbffa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PosisiRekening_RateBungaResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PosisiRekening_RateBungaResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac64ee7f-2d37-459f-afc0-448bdc7f5ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control nominal rateBungaDesimalDigits</value>
      <webElementGuid>22a83f3a-25f0-413f-8f7e-b93f6333c5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a4a9b068-86ed-4372-aebb-52520c7e4026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field RateBungaResult must be a number.</value>
      <webElementGuid>34acc603-d42e-4503-b554-c2678ca9d9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PosisiRekening_RateBungaResult</value>
      <webElementGuid>17cd1831-ef36-4e43-85e8-0a8b38e86158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PosisiRekening.RateBungaResult</value>
      <webElementGuid>9791b68f-faa1-4917-ae19-c2b814cd10c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rate Bunga Menjadi</value>
      <webElementGuid>ec4dba4c-3c09-48b3-8778-9eff5cad44b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>174e7567-70c3-452f-a501-a451f93dbed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cd2ec4a3-4c88-4107-b333-8e8f0ac0cfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PosisiRekening_RateBungaResult&quot;)</value>
      <webElementGuid>e267032d-1110-453d-bb54-4d78ec8c1314</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PosisiRekening_RateBungaResult']</value>
      <webElementGuid>942bedd2-9744-4389-8d10-e90eb68dc1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='posisiRekeningTable']/tbody/tr[3]/td[4]/div/input</value>
      <webElementGuid>839a82ba-9132-4bf9-a5f6-684bf8cd1540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/input</value>
      <webElementGuid>6af95d0e-2b8f-419c-8b9c-848ea38012cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PosisiRekening_RateBungaResult' and @name = 'PosisiRekening.RateBungaResult' and @placeholder = 'Rate Bunga Menjadi' and @type = 'text']</value>
      <webElementGuid>2146b9bb-6208-42f0-8318-ed7c4249b0e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
